### ISSUE TITLE
allowMultiple by default option?

### ISSUE THREAD

**Issue by reywright** [gajus/react-css-modules#101]
I like using multiple classes on my components... it seems weird if you allow that feature, that you would have to enable it on every single component that uses it. Can't there be some way that we can get this more easily enabled on a global scale by default?

**Comment by gajus** [comment]
* Use a global variable if you must to control the setting on all `react-css-modules` declarations.
* Use decorator pattern to abstract `react-css-modules` constructor.
* etc.

There are a lot of ways to abstract the issue.

**Comment by mightyspaj** [comment]
@gajus I disagree. Those solutions work fine, but it'd be cleaner to be able to configure global options in one place, instead of using a global variable or custom decorator in every component that uses `react-css-modules`.
