### ISSUE TITLE
Pure render logic fails on props.styles

### ISSUE THREAD

**Issue by liady** [gajus/react-css-modules#102]
Since `extendReactClass.js` sets `this.props.styles = { ... }`, pure render logic will always fail.

On every cycle, when shallow comparing current props to newly received props, even if nothing changed, current props will always have `styles: {...}` and new props will have `styles:undefined`.

**Comment by texttechne** [comment]
Wow, just found that out myself. This is a huge issue in regards to performance optimization: Using [PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html) becomes pointless. And this is the first best thing to do to prevent rerendering entire subtrees.

Seems to be another side effect of dynamically injecting the style property (compare #50). IMHO would be best to not do that at all.

**Comment by liady** [comment]
Indeed. I submitted a PR #103 to try and fix it, hopefully it will get merged

**Comment by gajus** [comment]
Would be nice to have a test case for this.

**Comment by texttechne** [comment]
Issue is closed, but bugfix is not released yet.
@gajus Any plans on releasing this? IMHO this is quite a show stopper...

**Comment by gajus** [comment]
> Issue is closed, but bugfix is not released yet.
> @gajus Any plans on releasing this? IMHO this is quite a show stopper...

I have rushed to close/ merge this (and I can no longer revert it). I am not going to release this until there is a test case covering the addition.

**Comment by liady** [comment]
Added the test - PR #108

**Comment by gajus** [comment]
@liady Thank you. This is a major improvement. v3.7.6 has been published.
