### ISSUE TITLE
When passing-through props to a child element, `styles` is included and overrides that element styles

### ISSUE THREAD

**Issue by liady** [gajus/react-css-modules#105]
When passing pass-through props to child element:
```js
const Header=({onClick, ...rest}) => 
  <div styleName='main' onClick={onClick}>
    <Title {...rest} />
  </div>
```

The child element gets `styles` in his props (since it is added before the render method of the parent), so it [overrides its own styles](https://github.com/gajus/react-css-modules/blob/master/src/extendReactClass.js#L19).

**Comment by gajus** [comment]
Duplicate of https://github.com/gajus/react-css-modules/issues/58
