### ISSUE TITLE
Getting an error "CSS module is undefined" when CSS module is defined.

### ISSUE THREAD

**Issue by export-mike** [gajus/react-css-modules#107]
finding that one component is failing to load.
the styles exist, the stylename prop is correct and yet I'm getting this error, any ideas? I'm using react-css-modules throughout my app.

Any information you have will be very helpful, thanks.

```Javascript
import React, {Component, PropTypes} from 'react';
import CssModules from 'react-css-modules';
import {FormattedMessage} from 'react-intl';
import Icon from '../Icon';
import styles from './styles.css';
import Address from '../Address';
console.log('STYLES', styles);
class LocationHeader extends Component {
  render() {
    return (<div styleName={'test'}>
      <Icon name={'location'} color={'casper'}/>
      <div>
        <h3 >{this.props.name}</h3>
        <Address {...this.props.address}/>
      </div>
      <div>
        <div>
          <span>
            <FormattedMessage id={'location.lat'}/> {this.props.lat}
          </span>
          <span>
            <FormattedMessage id={'location.lon'}/> {this.props.lon}
          </span>
        </div>
        <span>
          {this.props.notes}
        </span>
      </div>
    </div>);
  }
}

LocationHeader.propTypes = {
  name: PropTypes.string,
  address: PropTypes.object,
  lat: PropTypes.number,
  lon: PropTypes.number,
  notes: PropTypes.string
};

export default CssModules(LocationHeader, styles);
```

``` css
.test {
  background: green;
}
```

![image](https://cloud.githubusercontent.com/assets/2983327/13779325/4e6f4d5c-eab2-11e5-9f3c-7e9e50039f2c.png)

![image](https://cloud.githubusercontent.com/assets/2983327/13779334/560b00f6-eab2-11e5-9504-f5fdf8b557f4.png)

**Comment by export-mike** [comment]
FYI when I do it directly from a css module it works...

```import React, {Component, PropTypes} from 'react';
import {FormattedMessage} from 'react-intl';
import Icon from '../Icon';
import styles from './styles.css';
import Address from '../Address';

class LocationHeader extends Component {
  render() {
    return (<div className={styles.test}>
      <Icon name={'location'} color={'casper'}/>
      <div>
        <h3 >{this.props.name}</h3>
        <Address {...this.props.address}/>
      </div>
      <div>
        <div>
          <span>
            <FormattedMessage id={'location.lat'}/> {this.props.lat}
          </span>
          <span>
            <FormattedMessage id={'location.lon'}/> {this.props.lon}
          </span>
        </div>
        <span>
          {this.props.notes}
        </span>
      </div>
    </div>);
  }
}

LocationHeader.propTypes = {
  name: PropTypes.string,
  address: PropTypes.object,
  lat: PropTypes.number,
  lon: PropTypes.number,
  notes: PropTypes.string
};

export default LocationHeader;
```

**Comment by gajus** [comment]
Try this code:

```js
import React, {Component, PropTypes} from 'react';
import CssModules from 'react-css-modules';
import styles from './styles.css';
console.log('STYLES', styles);
class LocationHeader extends Component {
  render() {
    return <div styleName='test'></div>;
  }
}

export default CssModules(LocationHeader, styles);
```

and if the error persists, please share a full stack trace.

**Comment by joshfarrant** [comment]
I'm seeing the same thing
```css
/* Login.scss */
.test {
  background-color: red;
  width: 100px;
  height: 100px;
}
```

```jsx
// Login.js
import React from 'react';
import CSSModules from 'react-css-modules';
import styles from './Login.scss';

console.log('styles: ', styles);
// styles:  Object {test: "js-components-___Login__test___2hUgu"}

const Login = () => (
  <div styleName="test">
  </div>
);

export default CSSModules(Login);
```

The above produces the following

![screen shot 2016-03-15 at 15 16 55](https://cloud.githubusercontent.com/assets/6840861/13783051/9e7d2206-eac1-11e5-9899-3914653eb8c6.png)

However if I alter Login.js as follows then everything works as expected.

```jsx
// Login.js
import React from 'react';
import CSSModules from 'react-css-modules';
import styles from './Login.scss';

const Login = () => (
  <div className={styles.test}>
  </div>
);

export default CSSModules(Login);
```

**Comment by gajus** [comment]
I wonder if it has to do anything with the name of the class being "test". It is not a reserved keyword, though and looking at the https://github.com/gajus/react-css-modules/blob/3acb2efe9663068ea3399186e2345b9d1996c828/src/generateAppendClassName.js#L23-L33 I cannot see a reason why it would be not found if it exists in `styles` object.

**Comment by gajus** [comment]
@export-mike Please share the relevant CSS.

**Comment by gajus** [comment]
Oh, you have:

```css
.test {
  background-color: red;
  width: 100px;
  height: 100px;
}
```

**Comment by gajus** [comment]
I have just tried replicating and it appears to be working completely fine.

The version of react-css-modules that you are using, is it v3.7.5?

**Comment by joshfarrant** [comment]
I'm on 3.7.5. I've just been testing with different class names (`.background`, `.form.`, etc.) and I'm still seeing the same behaviour.

**Comment by joshfarrant** [comment]
Looking at the code you referenced (generateAppendClassName) it appears that the problem is that the `styles` variable is undefined at that point, so there's no object to find the style in, which is odd because logging out the `styles` object in my code above works fine.

**Comment by joshfarrant** [comment]
Ah, as expected I'm an idiot...

```
// Nope
export default CSSModules(Login);
// Yep
export default CSSModules(Login, styles);
```

Not surprising that the styles aren't being applied!

**Comment by gajus** [comment]
Thats not the code I have asked to test (https://github.com/gajus/react-css-modules/issues/107#issuecomment-196821653). Furthermore, your original code example does include `, styles)`.

**Comment by joshfarrant** [comment]
Neither of my examples from my [first comment](https://github.com/gajus/react-css-modules/issues/107#issuecomment-196874638) pass the `styles` variable to the `CSSModules` function. Once I added that change my issue was resolved.

@export-mike did include `, styles)` in both of his examples ([1](https://github.com/gajus/react-css-modules/issues/107#issue-140973608), [2](https://github.com/gajus/react-css-modules/issues/107#issuecomment-196821094)), so I would imagine further testing needs to be done with him.

Hope that helps clear things up!

**Comment by export-mike** [comment]
strange, so steps to replicate. take the code you have given above. have the webpack server running with the workaround code (not using react-css-modules) and paste in the code, replacing LocationHeader component. This will load. After that refresh. we get this error. 
this is the fullstack trace, 3xScreenshots.
![image](https://cloud.githubusercontent.com/assets/2983327/13785237/a5c393b6-eaca-11e5-8407-bb2b7a10023f.png)
![image](https://cloud.githubusercontent.com/assets/2983327/13785252/be4267dc-eaca-11e5-8191-26cdbd8c6b86.png)
![image](https://cloud.githubusercontent.com/assets/2983327/13785260/cbdf65c0-eaca-11e5-84e6-91eba67a0303.png)

**Comment by gajus** [comment]
> Neither of my examples from my first comment pass the styles variable to the CSSModules function. Once I added that change my issue was resolved.

Sorry, I did not notice that player 2 has entered the game.

**Comment by joshfarrant** [comment]
> Sorry, I did not notice that player 2 has entered the game.

No problem! :)

**Comment by gajus** [comment]
@export-mike In as many ways as I have tried to replicate this, I have not. Please setup a demo repository.

**Comment by export-mike** [comment]
good idea, thanks for your help :)

**Comment by gajus** [comment]
@export-mike Are you going to create a repository to replicate the issue?

**Comment by export-mike** [comment]
I was spreading props which contained  ```{...this.props}``` higher up overriding styles. now setting ```styles={null}```  when I spread.

**Comment by gajus** [comment]
`styles={null}` will have side effects. Consider using https://lodash.com/docs#remove to remove just `styles` property.

**Comment by gajus** [comment]
Forget what I have said. If you can sent styles to null then there is nothing wrong with this approach.

**Comment by CoreyTrombley** [comment]
Hey Peoples,

So I am currently getting this same error.

Here is the relevant [__Code__](https://gist.github.com/CoreyTrombley/516bde790f0dc046f54bddf5c271bf08) that I am using throughout. Please let me know if you see anything. I can not for the life of me get it to work. The Button component will render on its own, but when I try to render the button through a container or in any nested way it fails. Yet I have a Header component with its own styles that works fine, but as I am writing this, I am realizing that the header is not nested in the LaunchContainer. Did I do something incorrect with the nested components that load css-modules?

Again, thanks for any help!

##### Here are the local variables I have right before the error occurs.
<img width="446" alt="screenshot 2016-07-13 17 38 59" src="https://cloud.githubusercontent.com/assets/2028391/16820806/02548d60-4921-11e6-8f5a-08aaed6b8a4c.png">

**Comment by export-mike** [comment]
Are you spreading props from a parent onto this component causing the
styles to be undefined as parent component is also enhanced by CssModules?

**Comment by CoreyTrombley** [comment]
@export-mike I am not doing any spreading, but both components are using CSSModules.

**Comment by daisuke-3** [comment]
I had also got the same problem.
I had used spread props which contained `{...this.props}` .

So I send null to styles props, it worked fine.

**Comment by CoreyTrombley** [comment]
So what I have done in the mean time is just add `{errorWhenNotFound: false}` to the parent components of nested styled components.

**Comment by CoreyTrombley** [comment]
I found my issue. So my `Button` component had a prop that could be set `styleName` which of course is a reserved word for CSSModules. So once I changed that to `styleType` everything worked as expected.

**Comment by willdembinski** [comment]
Was this issue ever resolved?

**Comment by amalv** [comment]
I'm experiencing a similar issue too, here is the link to stackoverflow explaining the problem:

http://stackoverflow.com/questions/39852305/test-with-mocha-and-enzyme-a-react-component-that-uses-react-css-modules

Any help would be much appreciated, if anymore info is needed please just ask.

**Comment by export-mike** [comment]
@amalv looks like the issue has since been resolved in that SO question. The problem was with the test setup, previously I've used karma for testing with CSS modules, I never knew mocha has a styles mode you could enable. I'd like to try this out.

**Comment by export-mike** [comment]
Ha was unsure if this was closed or not, I can see it was closed, now closkng
