### ISSUE TITLE
How to import multiple css files?

### ISSUE THREAD

**Issue by zhaotoday** [gajus/react-css-modules#109]
How to import multiple css files in one react component?

**Comment by gajus** [comment]
```js
import styles1 from './styles1.css';
import styles2 from './styles2.css';
```

**Comment by grammka** [comment]
@gajus and? `@CSSModules(styles1, ....)` ? Or you mean we need to merge styles to one object?

**Comment by gajus** [comment]
> @gajus and? @CSSModules(styles1, ....) ? Or you mean we need to merge styles to one object?

`react-css-modules` is used to import already existing CSS modules object. It does nothing about combining styles, extending styles, etc. In general, this should be done at the CSS module level using [composition pattern](https://github.com/css-modules/css-modules#composition).

**Comment by grammka** [comment]
@gajus I see, thx for ur answer.
