### ISSUE TITLE
Mention need for npm install on readme

### ISSUE THREAD

**Issue by skitterm** [gajus/react-css-modules#111]
After trying a few things, I finally realized I needed to npm-install react-css-modules. It wasn't clear from the docs that that would be necessary. I inferred it by the `import .. from .. ` statement, but mentioning that as step 0 would be great.

**Comment by gajus** [comment]
Thats just too basic of a knowledge to include in the documentation. It is important to keep documentation length within reason and including a mention of `npm install` for most people will mean just adding extra noise.

Besides, using certain setups, `npm install` is not even necessary. If I am not mistaken, http://jspm.io/ automatically manages installation of dependencies.
