### ISSUE TITLE
Module not found: Error: Cannot resolve module 'lodash/collection/filter' in  @ ./~/react-css-modules/dist//index.js 7:19-47

### ISSUE THREAD

**Issue by barrysteyn** [gajus/react-css-modules#113]
It seems like this issue has come back. I am using version `3.7.6`. I am using NPM version `2.14.3` and I am using Node version `4.1.0`

**Comment by IanVS** [comment]
I am seeing the same errors with

```
npm 3.8.6
node 5.11.0
```

**Comment by gajus** [comment]
lodash is a dependency, https://github.com/gajus/react-css-modules/blob/e1b4a3da4667a7324a5d6f53f8895be6dc61f7ca/package.json#L25. Therefore, there is no reason to get this error. Chances are that NPM install step is failing.

Try running `npm install` twice.

**Comment by gajus** [comment]
Oh, this is a different error.

**Comment by IanVS** [comment]
Actually another `npm i` did fix this for me.  Not sure why I got in the weird state I was in.  I think you can close this.

**Comment by IanVS** [comment]
Oh interesting, I get the error when using npm `3.3.8`, but is fixed when I use `3.8.6`, so I guess it was an npm bug.
