### ISSUE TITLE
Styling (child) nodes in third party components

### ISSUE THREAD

**Issue by tomdmaguire** [gajus/react-css-modules#119]
Firstly I am aware that the title of this issue is similar to some previously closed issues and also to some sections of the documentation - I don't think it fits into those categories, but apologies in advance if this is just a case of me misunderstanding.

I am currently having trouble styling a third party component. For example, given a hypothetical component such as:

```js
import { Component } from 'react';
export default class FormWithButton extends Component {
  render() {
    return (
      <form>
        {this.props.children}
        <button className="btn">Save</button>
      </form>
    );
  }
}
```

I am unable to style the `<form>` and `<button>` elements.

I have tried the following without success, due to the `<button>` not having the same class name as the class name that is generated by my component with css module namespacing.

```js
import { Component } from 'react';
import FormWithButton from 'form-with-button';
import customStyles from './custom-styles.css';

class MyComponent extends Component {
  render() {
    return (
      <FormWithButton styles={customStyles}>
        <input name="test" />
      </FormWithButton>
    );
  }
}
```

Is there any way I would be able to style the `<form>` and `<button>` elements in this scenario given that the FormWithButton component is not wrapped with react-css-modules?

Thanks

**Comment by nkbt** [comment]
for such components (that do not pass class names properly) you would need to wrap it into your own container and use `:global` like:

```jsx
import customStyles from './custom-styles.css';

class MyComponent extends Component {
  render() {
    return (
      <div className={customStyles.formWrapper}>
        <FormWithButton styles={customStyles}>
          <input name="test" />
        </FormWithButton>
     </div>
    );
  }
}
```

```css
.formWrapper :global form {}
.formWrapper :global form > button {}
```

**Comment by gajus** [comment]
Note that if you are using a CSS pre-processor, such as SCSS, you can nest these declaration to avoid duplication, e.g.

```css
.formWrapper :global form {
    .foo {}
    .bar {}
}
```

**Comment by tomdmaguire** [comment]
Awesome, thanks!
