### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by levrik** [gajus/react-css-modules#122]
I'm getting `Uncaught TypeError: Cannot call a class as a function` with this code
```javascript
import React from 'react';
import CSSModules from 'react-css-modules';

import styles from './Titlebar.scss';

@CSSModules(styles)
export default class Titlebar extends React.Component {
  render = () => {
    return (
      <header>

      </header>
    )
  }
}
```

Using react-css-modules 3.7.6 and React 15

**Comment by enjoijkee** [comment]
Got same trouble

**Comment by enjoijkee** [comment]
@levrik If you found the solution please tell me about it, thanks.

**Comment by Mosho1** [comment]
@levrik @enjoijkee can you provide complete code with which to reproduce this?

**Comment by levrik** [comment]
Not more needed besides the SCSS file. It's completly regardless of how the content of the SCSS looks like.

Titlebar.scss
```scss
header {
   background-color:red;
}
```

**Comment by Mosho1** [comment]
I tried to reproduce the problem and couldn't in a fresh repo

**Comment by levrik** [comment]
Sorry. I don't have the code anymore. Also I'm not using this library anymore. If someone also have the problem please open a new issue. I'm closing this now.

**Comment by Kushan-** [comment]
Getting the same issue.Please help


import React from 'react';



 
class Authentication extends React.Component {
     render() {
         
         
         return <div>Hello, world</div>
     }
   
 }
 
 export default Authentication;
