### ISSUE TITLE
CSS import order is wrong

### ISSUE THREAD

**Issue by FezVrasta** [gajus/react-css-modules#125]
I need to manually include some CSS stylesheets (reset-css and material-design-icons), they should be loaded before my CSS modules to avoid specificity problems.

The problem is that the `style` tags are created in the opposite order of the one defined in my source files.

```js
require('material-design-icons-iconfont/dist/material-design-icons.css')
require('reset-css/reset.css')

import React from 'react'
import { render } from 'react-dom'

// components
import App from './pages/App'

render((<App />), document.getElementById('root'))
```

It results in:

```
<style>/* App.css */</style>
<style>/* material-design-icons.css</style>
<style>/* reset.css</style>
```

How can I fix this problem?

I thought I could import the `css` files using `import` in the `App.styl`, but it would be loaded as last `<style>` if I have more than one CSS module..

**Comment by gajus** [comment]
This behavior is not a result of using react-css-modules. Refer to https://github.com/webpack/css-loader.
