### ISSUE TITLE
Document internal behaviour with external effects

### ISSUE THREAD

**Issue by grrowl** [gajus/react-css-modules#128]
It was quite a surprise to learn about the behaviour and certain pitfalls/caveats of this library, including:

* Decorating a component will pass a `styles` property down through each of its children, until it encounters _another_ CSSModules wrapped component.
  * This means existing `styles` properties will break your application
* Hence, use of `{ ...this.props }` is considered harmful because your child component will adopt the stylesheet of its parent, _instead_ of the styles defined in the child component's own CSSModules wrapper.
  * Presents as seemingly unrelated incorrect "...is not found" exceptions
  * Unclear if it's dangerous to do this for _any_ component, or just for CSSModulesWrappedComponent spreading onto another CSSModulesWrappedComponent

It would be great if these (especially the `styles` property injection) were documented in the README.

**Comment by gajus** [comment]
They are documented:

* https://github.com/gajus/react-css-modules#styles-property
* https://github.com/gajus/react-css-modules#loops-and-child-components

For others reference, implications of using`{...this.props}` are discussed https://github.com/gajus/react-css-modules/issues/58.

As for your comment:

> Hence, use of `{ ...this.props }` is considered harmful because your child component will adopt the stylesheet of its parent, instead of the styles defined in the child component's own CSSModules wrapper.

The latter is not a design issue of `react-css-modules`:

* `styles` property is injected to allow access to the instance style map.
* You are explicitly passing down all the properties `{ ...this.props }`.
* You are complaining that child inherits `styles` property.

What is the logic in that?

If you want to exclude a property, you can do that:

```js
<AnotherComponent {...this.props} styles={null} />
```

This is user-land design issue.
