### ISSUE TITLE
Calling _.filter with only one arg breaks with lodash-webpack-plugin

### ISSUE THREAD

**Issue by ekosz** [gajus/react-css-modules#131]
So I just discovered this very strange bug with `react-css-modules` after upgrading to lodash 4.x. With my upgrade I also started using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) and [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) to help reduce the size of my builds. But afterwords I started get errors from `parseStyleName.js`.

<img width="899" alt="screen shot 2016-05-25 at 8 31 50 pm" src="https://cloud.githubusercontent.com/assets/212829/15562910/64e979d4-22b8-11e6-8b94-2ef995e402c6.png">

And after drilling into the filter method it was calling I found:

<img width="963" alt="screen shot 2016-05-25 at 8 32 01 pm" src="https://cloud.githubusercontent.com/assets/212829/15562920/7a43a49e-22b8-11e6-9bfa-377614ca4776.png">

It seems this version of `filter` that is being called requires a predicate method to be passed in with the collection, and blows up without it. But it looks like this library doesn't do that. I also consulted the docs and it seems that `_.filter` was never meant to be called with only one argument.

What was the original reason for having that line of code? I can't seem to tell what it does as written.

**Comment by gajus** [comment]
The original intent would have been to remove falsey values. When filter is invoked without a callback function, I expect the iterator to return the value that it has received as a parameter. Is that not the case?

**Comment by ekosz** [comment]
Ah, that use case seems more like [`_.compact`](https://lodash.com/docs#compact) than `_.filter`. Reading the docs it seems that `_.filter` defaults its predicate to [`_.identity`](https://lodash.com/docs#identity), which I don't think would remove falsey values.

**Comment by gajus** [comment]
It would return the value itself. If value is falsey, filter will remove it. At least thats the theory. You say it is broken. I will look into it.

**Comment by gajus** [comment]
Keep in mind though that react-css-modules is fairly popular package. I have not released any updates for several months now. It would be odd if you were the only one running into a bug.

**Comment by ekosz** [comment]
@gajus That's fair. I've already fixed the issue by removing the webpack plugin. I'm happy to close the issue. Just thought I should report my findings and get them indexed by google in case anyone else comes across the issue in the future and gets as confused as me.

**Comment by gajus** [comment]
:+1:

**Comment by wangyun** [comment]
I meet the same error when I enable lodash-webpack-plugin, 

"lodash": "^4.17.4",
"react-css-modules": "^3.7.10",
"lodash-webpack-plugin": "^0.10.6",
"babel-plugin-lodash": "^3.2.11",

**Comment by wangyun** [comment]
steps to reproduce：

install create-react-app
```
sudo npm install -g create-react-app
```

create test project
```
create-react-app filter-error
cd filter-error
npm run eject // and answer yes
npm i --only=dev
npm i --save-dev lodash-webpack-plugin
npm i --save react-css-modules
```

modify file: config/wepack.config.dev.js
add
```
var LodashModuleReplacementPlugin = require('lodash-webpack-plugin');
```
to the top and
```
new LodashModuleReplacementPlugin,
```
into the plugins array

modify src/App.js
add
```
import _ from 'lodash';
```
to the top, and
```
console.log(_.chunk([1,2,3,4], 2));
```
into the top of the render function

run the dev server
```
yarn start
```
this will open browser and navigate home page, it works
now add react-css-modules, also modify src/App.js
change import './App.css'; to
```
import cssModules from 'react-css-modules';
import styles from './App.css';
```
change export default App; to
```
export default cssModules(App, styles);
```
and change all ```className``` to ```styleName```
run yarn start again, and error happens:

```
Uncaught TypeError: predicate is not a function
arrayFilter @ filter.js:18
exports.default @ parseStyleName.js:26
...
```

**Comment by wangyun** [comment]
I found the reason now:)
I should add some feature sets to the plugin
new LodashModuleReplacementPlugin({
      shorthands: true,
      collections: true,
    }),

problem solved!
Please close this issue, thanks.

**Comment by axe312ger** [comment]
@wangyun thank you so much! :)
