### ISSUE TITLE
Using es6-map

### ISSUE THREAD

**Issue by Mosho1** [gajus/react-css-modules#133]
Using es6-map bumps up my code size considerably (55kb unminified), would you consider not using it? I don't think the usage here justifies the cost.

**Comment by gajus** [comment]
If you can propose an alternative implementation that achieves the same result, I will happily consider it.

**Comment by Mosho1** [comment]
Made a PR, the implementation is as simple as it can get, and all tests pass.

**Comment by gajus** [comment]
PR merged. v3.7.7 released. Thank you.
