### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by RichardJECooke** [gajus/react-css-modules#137]
Hi, it looks like your .js files are actually Typescript as they have types inside them.   But I can't find a Typings definition file anywhere for this project.

Are these definitions in another library somewhere, or missing in this project's readme?

I'm having trouble using react-css-modules without definitions: http://stackoverflow.com/questions/37675920/jsx-element-type-does-not-have-any-construct-or-call-signatures/37676736#37676736

**Comment by gajus** [comment]
We are not using TS. The annotations that you see are Flow type annotations and they are not in production build.

**Comment by BeeZet** [comment]
Hi, I created typings for decorator syntax, but it can be easily extended with function constructor.

Here's gist with declaration and example usage: https://gist.github.com/BeeZet/24026f8130a0fdee7a9d83117023c695

**Comment by varHarrie** [comment]
@BeeZet 
```
Property 'styleName' does not exist on type 'HTMLProps<HTMLDivElement>'
```

How to solve this problem?
