### ISSUE TITLE
Use Higher-order Component (HoC) to abstract react-css-modules

### ISSUE THREAD

**Issue by sstur** [gajus/react-css-modules#138]
I like the idea of `react-css-modules` but the implementation, specifically within `extendReactClass` is inherently flawed. By this I mean you should NOT subclass a React component because it will break assumptions that developers and other library authors make. Instead you should use a Higher Order Component.

Also, you should not mutate props within `render` (or anywhere) but that is not the primary issue I've experienced.

I will attempt to identify the problem and propose a solution. I believe this is fundamentally the issue behind #99 also.

Problem:
```js
class Foo extends Component {
  constructor() {
    super(...arguments);
    let myProto = Object.getPrototypeOf(this);
    console.log(myProto === Foo.prototype); // Should be true.
    console.log(Object.getOwnPropertyNames(myProto)); // Should be the list of methods in this class.
  }
  render() { ... }
  /* ... other methods ... */
}

class SubFoo extends Foo {
  // Bad practice. Should not do. Essentially this is what `react-css-modules` does
}
```

Essentially you are modifying the prototype chain by subclassing a React component which is not a commonly accepted practice and should probably be avoided in favor of using Higher Order Components (see below). I expect there are other things that can go wrong when you do this (especially when mutating `props`), but the problem I specifically ran into was with `getPrototypeOf` which was uncovered by an issue filed in [class-autobind](https://github.com/kodefox/class-autobind).

The preferred way to do things like modifying props, is to create a new component that defers rendering the given component and optionally returns new output from `render`. This is commonly referred to has a Higher Order Component:

```js
function getHoC(OldComponent, coolStyles) {
  class NewComponent extends React.Component {
    render() {
      let output = <OldComponent {...this.props} />;
      return doCoolStuff(output, coolStyles);
    }
  }
  // Optionally copy static stuff to NewComponent.
  return NewComponent;
}
```

Remember that `output` is a plain object (element) in React, so `doCoolStuff()` could presumably create a new plain object with different or additional props than `output` had but it should NOT mutate output in any way.

Are you interested in a pull request to this effect?

**Comment by gajus** [comment]
> [..] which is not a commonly accepted practice and should probably be avoided in favor of using Higher Order Components (see below)

Source?

> I expect there are other things that can go wrong when you do this (especially when mutating props),

Please do not spread FUD. If you have a specific issue that you'd like to discuss, please bring it to my attention.

> but the problem I specifically ran into was with getPrototypeOf which was uncovered by an issue filed in class-autobind.

What issue?

> The preferred

Thats subjective.

>  [..] way to do things like modifying props, is to create a new component that defers rendering the given component and optionally returns new output from render. This is commonly referred to has a Higher Order Component:

The end result is virtually the same. HOC has a greater overhead.

> I believe this is fundamentally the issue behind #99 also.

Regarding the specific issue that you have referred to (https://github.com/gajus/react-css-modules/issues/99), to quote the [documentation](https://facebook.github.io/react/docs/context.html):

> Context is an advanced and experimental feature. The API is likely to change in future releases.
> Most applications will never need to use context. [..]
> If you have to use context, use it sparingly.
> [..]

The reason to concern with React context until it is stable.

> Are you interested in a pull request to this effect?

Not at this stage. Only if there is a case for it.

**Comment by sstur** [comment]
I'll try to get some better sources for the "not a commonly accepted practice and should probably be avoided" stuff. It seems my issue might have come across more offensive than intended. I do believe the overhead of HOC is worth it in exchange for immutability, but like many tradeoffs (e.g. readability vs perf) it is largely subjective and this is only a suggestion.

**Comment by gajus** [comment]
> I do believe the overhead of HOC is worth it in exchange for immutability

Definition of immutability is:

> [..] an immutable object (unchangeable object) is an object whose state cannot be modified after it is created.

HOC does not achieve immutability. It adds additional abstraction on top of the subject component that it then extends with additional properties. The end result is that props object received by the target component is mutated regardless of whether you are using HOC or extend the `render` method.

**Comment by sstur** [comment]
I do not believe that definition of immutability is exhaustive. I believe you can achieve immutability even with changeable objects, simply by using a pattern of programming that chooses not to mutate them. For example, this is the way React expects programmers to deal with `this.state`. In the case of HOC, I will agree "HOC does not achieve immutability" but it certainly encourages it by choosing composition.

**Comment by sstur** [comment]
> The end result is that props object received by the target component is mutated regardless of whether you are using HOC or extend the render method.

I do not think the props object is mutated at all in HoC-style React. Can you cite an example?

**Comment by gajus** [comment]
> > The end result is that props object received by the target component is mutated regardless of whether you are using HOC or extend the render method.
> I do not think the props object is mutated at all in HoC-style React. Can you cite an example?

If you have time, raise a PR. It does not have to be polished, just a working prototype.

There was a good reason I did not proceed with HoC at the time. I cannot recall by quickly looking at the code.

**Comment by sstur** [comment]
Will do. Thanks!

**Comment by sstur** [comment]
I have utterly failed at producing a meaningful diff that will use HoC to accomplish what you're doing with react-css-modules.

I guess I would need some mechanism to intercept the render tree of `React.Element`s before React internally passes it to ReactDOM for reconciliation. But that's a total no-go.

I'd like to believe there's a way to do this with HoC but my brain is coming up blank. I'll have to defer to some React folks who know more than I do. If there's a better way, I'll post back here.

Thanks!

**Comment by gajus** [comment]
> I have utterly failed at producing a meaningful diff that will use HoC to accomplish what you're doing with react-css-modules.

Can you describe in few sentences whats the problem?

To use as a point of reference for the next fellow who suggests to use HoC.

**Comment by sstur** [comment]
Essentially, the HoC approach is well suited to intercepting the data being passed *to* a component, namely the props. What needs to be done for react-css-modules is to intercept the rendering tree returned *from* a component.

The error in my proposed solution was thinking that the result of `<Foo />` contains anything from Foo's render method (I actually know better, but it didn't occur to me until I started writing tests). The JSX syntax `<Foo {...props} />` (or the `React.createElement(...)` form) is really no more than a plain object like `{type: Foo, props: props}` which will lazily turn into an instance of Foo somewhere deep in React's internals.

```js
function getHoC(OldComponent, coolStyles) {
  class NewComponent extends React.Component {
    render() {
      let output = <OldComponent {...this.props} />;
      return doCoolStuff(output, coolStyles); // <== here output does NOT have the results of OldComponent's render method yet. It has no more information than we gave it (a component and a set of props). So `doCoolStuff()` can't really do anything useful.
    }
  }
  // Optionally copy static stuff to NewComponent.
  return NewComponent;
}
```

**Comment by sstur** [comment]
So if we wanted to do this in an immutable/composable way without subclassing the component, the API would have to be completely different than what react-css-modules's API is now.

Instead of:

```js
class Foo extends React.Component {
  render() {
    return <div styleName="foo">...</div>;
  }
}

export default wrap(Foo, coolStyles);
```

We'd have to wrap the return value inside the render method:

```js
class Foo extends React.Component {
  render() {
    return wrap(<div styleName="foo">...</div>, coolStyles);
  }
}

export default Foo;
```

That really would take away a lot of the magic of this library and it's more tedious if you have branching inside of render and what not.
