### ISSUE TITLE
Why styleName against className?

### ISSUE THREAD

**Issue by gyzerok** [gajus/react-css-modules#14]
Why?

**Comment by gajus** [comment]
`className` is used for CSS.

**Comment by gajus** [comment]
The first version of `react-css-modules` used to overload `className`. You were able to declare regular CSS and Interoperable CSS in the same declaration, e.g.

```js
<div className='foo bar' />
```

Where `foo` and `bar` could have been a CSS class, Interoperable CSS class, or both. The problem with this approach is that there is no way to distinguish between whether developer intention is to refer to a CSS class or Interoperable CSS class. Thus, a new convention has been suggested to use `styleName` for Interoperable CSS (CSS Modules) and leave `className` for CSS.

**Comment by gajus** [comment]
If you are interested to know why specifically `styleName`, as opposed to something else like (`cssModule`, `classModule`, etc.) then you need to forget everything you know about HTML and CSS for a moment. If you have an object and want to style that object in a specific way. That style would have a name. Therefore, `styleName` is more appropriate, even more appropriate than `className`.

**Comment by gyzerok** [comment]
@gajus Cant we just try to load class from css-modules and if there is no such fallback into simple css class (its about use only ```className```)? In my mind its just a problem of prioritising. Am I wrong?

**Comment by gyzerok** [comment]
So its up to developer not to create collisions between css-module classes and the global class system.

**Comment by gajus** [comment]
> So its up to developer not to create collisions between css-module classes and the global class system.

If it is up to the developer to avoid collisions, then how does a new developer determine this convention just by looking at the code? The code needs to be self-explanatory as much as possible.

**Comment by gajus** [comment]
You can view the earlier implementation here, https://github.com/gajus/react-css-modules/tree/5bff24ed38c4b30af7e011d97f829403acfcce74.

**Comment by gyzerok** [comment]
@ganjus I guess here is problem only with usage pattern. As I've understood css-modules idea you should know define global styles and use composition. If so, there is no problems with it. All your classes in className are css-module classes. With this in mind I guess that here is problem with "old" developer who uses css-modules in incorrect way.

**Comment by grabbou** [comment]
-1. I am ok with the current implementation as there's a clear distinction between a module and a normal, npm-downloaded css. The only issue I see with overloading is the collision handling in case multiple class names are provided. With the above, it's just easier to reason about.

**Comment by DrivingFatigue** [comment]
A clear explanation！！！！！
