### ISSUE TITLE
Mocha test of components throw errors related to css

### ISSUE THREAD

**Issue by msmfsd** [gajus/react-css-modules#142]
I really love this project and would like to suggest some integration with testing utilities. Mocha/Chai throws errors when testing components with CSSModules. There are some threads on how to ignore css completely when testing react components though this sound like a compromise to me.

Can I suggest either a argument to ignore on tests or a npm module ie. 'react-css-modules-mocha'?

Cheers.

**Comment by gajus** [comment]
> There are some threads on how to ignore css completely when testing react components though this sound like a compromise to me.

Please be specific when describing an error/ known issue. There are no known limitations in the current implementation of `react-css-modules` that would prevent testing using Mocha.

**Comment by msmfsd** [comment]
Fair call. Actually I think it lies with webpack/babel because if I use karma-webpack config there are no issues and when I use mocha/babel-core I get the errors. I will look into it today and close this issue.

**Comment by gajus** [comment]
Before closing and issue, please explain what you have discovered.
