### ISSUE TITLE
Feature: Array of styles

### ISSUE THREAD

**Issue by olegdizus** [gajus/react-css-modules#143]
Would be great if react-css-modules could accept array of styles.
Like this:
<Component styleName={['common-style', isActive ? 'active-style' : 'not-active-style']} />

This feature can be implemented by using .join(' '), but I think accepting array in styleName easiest and shortest way just out the box. Besides, we can implement more precise validation in module.

I created PR #141, so don't be shy vote if you think that feature would be useful.

----
This is reply to @gajus comment

**Comment by gajus** [comment]
As I said in the PR:

> In this particular case, what you want can be achieved using .join(' '). No need to explicitly accept array as a value.

However, I will leave the PR/ issue open to see what are the thoughts of the community about it.

**Comment by gajus** [comment]
PR closed.

Closing issue as this did not receive much attention.
