### ISSUE TITLE
Is there a working example of using sass-loader with extract-text-webpack-plugin and react-css-modules?

### ISSUE THREAD

**Issue by EdwardDrapkin** [gajus/react-css-modules#144]
I've tried seemingly every permutation of options to ExtractTextPlugin.extract() and I get some module loading failure or another... is there a working example of this anywhere?

Based on the docs, I figured this would work:

    loaders.push({
        test: /\.s?css$/,
        loaders: [
            ExtractTextPlugin.extract('style',
            'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass?config=sassLoader'),
        ]
    });

    plugins.push(new ExtractTextPlugin(path.resolve('public/css/extracted.css'), {
        allChunks: true
    }));

but it fails on one of my `@import` statements as an unexpected character, which seems to mean the sass loader isn't getting used?

Here's an example error

    ERROR in ./app/components/Application/HSBFooter.scss
    Module parse failed: /var/www/projects/hsb-app/proj/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style!css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass?config=sassLoader!/var/www/projects/hsb-app/proj/app/components/Application/HSBFooter.scss Unexpected character '@' (1:0)
    You may need an appropriate loader to handle this file type.
     | @import 'scss/global';

Building without extract-text-plugin works fine:

    loaders.push(
        {
            test: /\.s?css$/,
            loaders: [
                'style?sourceMap',
                'css?sourceMap&modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
                'sass?sourceMap&config=sassLoader'
            ]
        }
    );

**Comment by ramsaylanier** [comment]
This setup works for me.

https://github.com/ramsaylanier/WordPressExpress/blob/master/webpack.config.js

**Comment by EdwardDrapkin** [comment]
@ramsaylanier It doesn't look like you're calling ExtractTextPlugin.extract() anywhere?

**Comment by ramsaylanier** [comment]
Oh, I see. Why are you using the extract() function? You only need to use the extract() function if there is more than one usage of the ExtractTextPlugin, per the [API](https://github.com/webpack/extract-text-webpack-plugin#api).

**Comment by EdwardDrapkin** [comment]
@ramsaylanier you're not putting the plugin in your loaders, and you're not invoking it anywhere, how are you expecting it to work?  Does it actually extract your css modules?  I tried what you're doing and only instantiated it in plugins and it just got completely ignored, as I'd expect, since it's not getting put in the loader chain anywhere.  Are you sure this works and extracts the CSS to a separate file?

**Comment by ramsaylanier** [comment]
@EdwardDrapkin yes I am sure. Here is a screen shot of the app I'm working on. You can see that the css gets extracted into an app.min.css file.

<img width="1440" alt="screen shot 2016-06-29 at 9 16 24 am" src="https://cloud.githubusercontent.com/assets/2359852/16453269/43f38052-3dda-11e6-835a-2620f918e69c.png">

**Comment by EdwardDrapkin** [comment]
That's not extracting your react-css-modules class definitions, that appears to be your global css definitions.

**Comment by ramsaylanier** [comment]
It isnt? .page__subtitle, .page__title are react-css-modules. 

https://github.com/ramsaylanier/WordPressExpress/blob/master/app/components/pages/page.scss

**Comment by EdwardDrapkin** [comment]
FFS, you're actually using the plugin correctly in another config file and arguing for its incorrect use: https://github.com/ramsaylanier/WordPressExpress/blob/master/webpack.production.config.js

**Comment by ramsaylanier** [comment]
My point is that both ways work. You're welcome.

**Comment by EdwardDrapkin** [comment]
When you don't put a plugin in the loader chain, it doesn't get invoked and can't work.  What you linked originally does not, and will not, work, and you've now wasted a tremendous amount of my time.  Furthermore, when I dug in your repository and found you using the plugin correctly, it still doesn't work for me, and I get the same issues.

Does anyone working on THIS project have an example of using extract-text-plugin with scss that they know is correct and working?

**Comment by ramsaylanier** [comment]
I did link to the wrong webpack config. I apologize for "wasting a tremendous amount of your time". However, the production config absolutely does work. Instead of being rude, maybe you can provide a link to a repository so someone can try to reproduce the error you are getting.

**Comment by EdwardDrapkin** [comment]
I fixed it by bypassing ETP's internal loader chain and just used webpack's loader chain instead...

   loaders.push({
        test: /\.s?css$/,
        loaders: [
            ExtractTextPlugin.extract('style'),
            'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
            'sass?sourceMap&config=sassLoader'
        ]
    });

    plugins.push(new ExtractTextPlugin('css/extracted.css', {
        allChunks: true
    }));

There's
