### ISSUE TITLE
Warning: unknown prop 'styleName'

### ISSUE THREAD

**Issue by a3gis** [gajus/react-css-modules#149]
Hello!

The library works as expected but I am getting a warning in the browser:

```bundle.js:1269 Warning: Unknown prop `styleName` on <div> tag. Remove this prop from the element```

Code:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import CSSModules from 'react-css-modules';

import styles from './hello.css';

// eslint-disable-next-line
let HelloMessage = React.createClass({
  propTypes: {
    name: React.PropTypes.string,
  },
  render() {
    return <div styleName="hello">Hello {this.props.name}</div>;
  },
});

let HelloMessageDecorated = CSSModules(HelloMessage, styles);

const mountNode = document.getElementById('app');

ReactDOM.render(<HelloMessageDecorated name="John" />, mountNode);
```

Any way around this?

Awesome work!

**Comment by gajus** [comment]
Please have a look at other open issues and close this issue (referencing the original issue) as duplicate.

**Comment by a3gis** [comment]
Oh yes, my apologies. Reference: https://github.com/gajus/react-css-modules/issues/147
