### ISSUE TITLE
Global styles with preprocessors

### ISSUE THREAD

**Issue by namxam** [gajus/react-css-modules#15]
I am not sure if I am doing it correctly, but I cannot get the global prefix to work with sass syntax.

I setup webpack like this:

    loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!autoprefixer!sass?indentedSyntax')

But when trying to prefix a style with ```:global```, sass fails to compile it. I tried to unquote it, but this does not seem to work as well.

Any ideas?

**Comment by gajus** [comment]
This question should be raised with https://github.com/webpack/style-loader.

As far as I remember, I did not experience problems doing:

```
:global .foo {
}
```

using the https://github.com/gajus/react-css-modules-examples setup.

**Comment by gajus** [comment]
I just tried that code snippet with http://sassmeister.com/ and it works as expected. Make sure that `sass-loader` module is installed.

**Comment by namxam** [comment]
Thanks for your quick reply. I will have another look at my setup. Obviously, I made some error :cry:

**Comment by namxam** [comment]
This is weird. It works on sassmeister, but not when using node-sass. I checked and it uses the same libsass version as on sassmeister. Using scss instead of sass, it works out of the box.

package.json

    "node-sass": "^3.3.2"

test.sass
```sass
:global .test
  background-color: #eee
```

Running command
```bash
./node_modules/node-sass/bin/node-sass -i test.sass test.css
```

yields
```json
{
  "message": "invalid top-level expression",
  "column": 1,
  "line": 1,
  "file": "/path-to-project/test.sass",
  "status": 1
}
```

I guess I will open an issue on node-sass about it. I just leave it here, for others to find.
