### ISSUE TITLE
After adding "babel-polyfill" got an error `Can't add property className, object is not extensible`

### ISSUE THREAD

**Issue by vasyanik** [gajus/react-css-modules#150]
While trying to solve an issue with browsers that don't support Symbol, I've added `babel-polyfill`
After that got an error:
`Uncaught TypeError: Can't add property className, object is not extensible`

at line `elementShallowCopy.props.className = appendClassName;`

```javascript
if (styleNames.length) {
    appendClassName = (0, _generateAppendClassName2.default)(styles, styleNames, configuration.errorWhenNotFound);

    if (appendClassName) {
        if (elementShallowCopy.props.className) {
            appendClassName = elementShallowCopy.props.className + ' ' + appendClassName;
        }

        elementShallowCopy.props.className = appendClassName;
        elementShallowCopy.props.styleName = null;
    }
}
```

Can I somehow fix this? :(

**Comment by gajus** [comment]
You shouldn't need `babel-polyfill` using v3.7.7 (Thanks to https://github.com/gajus/react-css-modules/pull/140)

**Comment by ufo22940268** [comment]
@gajus 

So without `babel-polyfill`  how can i compatible with old browser which doesn't have `Object.assign`?

**Comment by gajus** [comment]
@ufo22940268 Whats the relation between your question and this issue?

**Comment by ufo22940268** [comment]
@gajus sorry , my bad, it caused by babel.

**Comment by eric7578** [comment]
I have the same issue, but i need the babel-polyfill in order to run the redux-saga, any work around suggestions? ;)
