### ISSUE TITLE
react Warning: Unknown prop `styleName`

### ISSUE THREAD

**Issue by joeshub** [gajus/react-css-modules#153]
Switched to **react & react-dom 15.2.0**

Now react-css-modules is being nagged to regarding the **styleName** attribute not being a proper attribute.

Found a few other projects complaining about the same thing. Let's try to come up with a fix for people using react-css-modules

https://github.com/react-toolbox/react-toolbox/issues/607
https://github.com/Hacker0x01/react-datepicker/issues/517
https://github.com/erikras/redux-form/issues/1249#issuecomment-230324048

**Comment by gajus** [comment]
@joeshub Please search the issue thread and close this issue as duplicate once you find an existing issue.

**Comment by joeshub** [comment]
My bad. Just found #147 and #148

Thank you

Upgrading to v3.7.7
