### ISSUE TITLE
Map.prototype.set returns with undefined in internet explorer 11

### ISSUE THREAD

**Issue by balaxy** [gajus/react-css-modules#157]
I'm trying to build a react application, and use react-css-modules. Everything runs fine under FF and Chrome, but in IE11 I encounter the following issue, at page loading I get the following exception message:

Unable to get property 'set' of undefined or null reference

It seems that the issue occurs in _generateAppendClassname_ (line 37) of the react-css-modules, where the _stylesIndexMap_ will remain undefined. It seems that the following operation will set undefined for the Map.

`stylesIndexMap = stylesIndex.set(styles, new _simpleMap2.default());`

Seems that IE11 does not support yet the _Map.prototype.set returns this_ functionality. Is it possible to change the implementation that it is not relying on the set return value?

**Comment by gajus** [comment]
This issue has been raised before. Please search for an existing issue describing this behaviour. When found, please close this issue as a duplicate and reference the original issue. If the original issue is closed, please ensure that you are using the latest version of the package. If you are, please add a comment to the existing issue thread mentioning the version number and the behaviour.

**Comment by balaxy** [comment]
I found only one related issue [https://github.com/gajus/react-css-modules/issues/133], but this is about changing the implementation of Map from ES6Map to something else.

 I'm using the latest version(3.7.7) which is including the _simplemap_ implementation.  Since in IE11 the map implementation is there it will use that, but not the Simplemap. Unfortunately the IE11 version does not support the the Map.prototype.set returns this and therefore the exception happens.

**Comment by gajus** [comment]
I have only glanced through. Though are you sure that your issue is not https://github.com/gajus/react-css-modules/issues/84 ?

**Comment by balaxy** [comment]
Tbh I'm new to this world :), I'm not a 100% sure that the origin of the problem is not the same.

I only know, that when I set up a break point to line 18. of the  [generateAppendClassName.js file ](https://github.com/gajus/react-css-modules/blob/master/src/generateAppendClassName.js) and hit on step the _stylesIndexMap _ will be still undefined. According to 
[this compatibility table](https://kangax.github.io/compat-table/es6/) IE11 supports Map, but the .set function will not return with this, so that was my best guess why i get the exception.

**Comment by ZeroCho** [comment]
@gajus I have the same problem and @balaxy 's fix solved this.

**Comment by chrisvanmook** [comment]
@gajus I can also confirm @balaxy 's fix worked for me

**Comment by MorrisGallego** [comment]
Any update on this? I have the same issue

**Comment by weblogixx** [comment]
When using webpack, you may "fix" this tempory by adding babel-polyfill. If it is included, it will not break in IE11. I would also hope the fix will be included soon :(

**Comment by gajus** [comment]
The current PR does not pass the CI, therefore I cannot merge it. If someone were to fix the issue and raise a PR, I'd be happy to merge it.

**Comment by weblogixx** [comment]
I will update it. Unfortunately I do not know how I can create a PR for a PR, so I will fork it for my own.

**Comment by apreg** [comment]
Could you merge @weblogixx 's commit so I can start using it.

**Comment by gajus** [comment]
@apreg Done. Thank you @weblogixx
