### ISSUE TITLE
3.0.4 not working

### ISSUE THREAD

**Issue by nsisodiya** [gajus/react-css-modules#16]
my codebase working, but it stopped working now, I am searching a lot, I found, I did a npm update.
I checked out a new version, Please let me know what changes you have done, my project stopped rendering classes.

**Comment by gajus** [comment]
As a temporary fix please revert back to 3.0.3. I will look into this asap.

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/tree/3.0.5 added test cases to make sure this does not happen again.
