### ISSUE TITLE
Doesn't work with cq-prolyfille

### ISSUE THREAD

**Issue by QuietOmen** [gajus/react-css-modules#168]
I'd like to use react-css-modules as I love creating unique selectors for my components. However, I also love the idea of using cq-prolyfill along side it. The problem is that cq-prolyfill uses javascript to catch resolution changes in the dom to trigger changes in the styles. It looks for a specific pattern to see what queries match up, but these are getting changed by react-css-modules. It would be nice to specify a pattern that you wouldn't want react-css-modules to change and they'd remain the same. For example, right now this: 

   ```.input-wrapper:container(width >=100px) { /* ... */}```

gets changed to this: 

   ```.styles__input-wrapper___2xh6W.styles__-container-width--100px-___PPtoO {/* ... */}```

it would be nice to ignore all styles that match the pattern ```:container```

**Comment by gajus** [comment]
> @gajus I agree that tests should be build environment agnostic. However, descriptive test results, in my opinion, are important to have. As the problem can be found just skimming through them.

Just use `:global` switch https://github.com/css-modules/css-modules#exceptions.

**Comment by QuietOmen** [comment]
@gajus I don't think wrapping it in :global is sufficient. This would cause the styles inside it to not get clobbered by the name, but the normal styles would have their names hashed. So in my example, I'm using a common name called ```input``` for the base styles, so I definitely want it to hash the class name to assure that it won't get overridden by global/other styles the user creates. So

```
.input {
   /* base styles with common class name were hashing is needed */
}

.input:container {
  /*cq-prolyfil styles where we need the :container (width <= 100px) to not be altered*/
}
```
But then I don't want the container portion to remain the same. Does this make sense? Am I missing something here?

**Comment by gajus** [comment]
Can you produce desired input and output example?

**Comment by gajus** [comment]
> it would be nice to ignore all styles that match the pattern :container

Oh, I misread the original requirement.

The problem is that:

```css
.input-wrapper:container(width >=100px) {}
```

gets converted to:

```css
.styles__input-wrapper___2xh6W.styles__-container-width--100px-___PPtoO {}
```

when the desired output is:

```css
.styles__input-wrapper___2xh6W:container(width >=100px) {}
```

This is outside the scope of https://github.com/gajus/react-css-modules. Rules governing parsing of the CSS classes are down to the implementation of the CSS loader.

If you are using webpack, this issue most likely belongs in [style-loader](https://github.com/webpack/style-loader).

**Comment by QuietOmen** [comment]
Thanks, for the feedback. I'll discuss it over there and see if I can find a solution. If I do, then I'll post it back on here, or come back if I discover something new.
