### ISSUE TITLE
Change lodash dependency to import only functions that are used

### ISSUE THREAD

**Issue by dntrkv** [gajus/react-css-modules#169]
First off wanted to say thanks for maintaining this project, it's been super useful.

One issue that I have run into with the project is how the lodash is included. Since the whole package is included when you do:

`import _ from 'lodash'`

And lodash assigns itself to the global `_` variable, even if you use webpack to build your bundle, it still binds to the global variable which has been breaking a ton of legacy pages on my project which still use the global.

There are a couple ways to fix this, one being the `_.noConflict` option, but the option which I think is preferable is to only import the lodash functions that the project really needs.

e.g. instead of `import _ from 'lodash` we can do `import isFunction from 'lodash/isFunction'`

This would resolve the issue of binding to the global variable and also it would reduce the package size in cases where the project doesn't already have lodash as a dependency.

Let me know what you think, if this is something you would like to do, I can open a PR.

Thanks

Dan

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/blob/478f0e6ff27317fdd5e62e60500d30a1734fcb6c/.babelrc#L9
