### ISSUE TITLE
Why do I have to wrap :local

### ISSUE THREAD

**Issue by rlesniak** [gajus/react-css-modules#176]
Hi,

can anyone help me? To make things work I have to wrap every scss file by `:local` pseudoclass.
My config: 
`  loader: 'style!css?modules&sourceMap&localIdentName=[local]___[hash:base64:5]!resolve-url!sass?outputStyle=expanded&sourceMap'`  

What I need to do to get rid of this constraint?

**Comment by gajus** [comment]
Refer to the `css-loader` documentation.

https://github.com/webpack/css-loader#local-scope
