### ISSUE TITLE
More readable UIDs in class names

### ISSUE THREAD

**Issue by lluia** [gajus/react-css-modules#177]
Hi,

First of all, congrats for the great work with **react-css-modules**! 👏 🙌  😄

Not sure if this relates to this module or just to **css-modules**.

It would be nice if we could generate more readable unique class names. 
Right now the generated class names look something like:

```html
<span class="src-components-Range-___unit___KKJ2w src-components-Range-___range__unit___-fqq8">€</span>
```  
I wonder if we could generate something like: 

```html
<span class="components-range-unit-4e1f75cd11e68b77">€</span>
```  
So the formula will be something like:

```html
<span class="components-[component name]-[class name from styles object]-[unique ID]">€</span>
```  
In this way, when debugging the DOM on browser's *devtools* everything gets more readable:
```html
<div class="components-price-base-4e1f75cd11e68b77">
  <span class="components-price-value-4e1f75cd11e68b77">3000</span>
  <span class="components-price-unit-4e1f75cd11e68b77">€</span>
</div>
``` 
Not sure if it's possible and happy to help if needed,  
Cheers!

**Comment by gajus** [comment]
You can already do this.

Refer to [`localIdentName` setting](https://github.com/webpack/css-loader) if you are using `css-loader`.

Refer to [`generateScopedName` settings](https://github.com/css-modules/postcss-modules#generating-scoped-names) if you are using `postcss-modules`.

**Comment by lluia** [comment]
iups true, thanks for pointing out!
