### ISSUE TITLE
Dead code elimination 

### ISSUE THREAD

**Issue by dntrkv** [gajus/react-css-modules#180]
How feasible would it be to add a dead code elimination feature to the project? Basically, it would either drop the unused modules from the final stylesheet or it would just throw a warning in the console the same way it does when you try to use an undefined module. This would be a killer feature.

One difficult aspect of this feature I can foresee is that a single stylesheet can be shared across components. So you would have to remember which modules are used in other components.

Also, is this a feature that should go into css-modules, rather than this project?

**Comment by gajus** [comment]
Outside of scope of this project. This belongs in the css-loader or whatever else the underlying loader is.
