### ISSUE TITLE
source map not working

### ISSUE THREAD

**Issue by craigcosmo** [gajus/react-css-modules#184]
my config

```js
{
	test: /\.scss$/,
	loader: ExtractTextPlugin.extract('style?sourceMap','css?modules&importLoaders=1&localIdentName=[local]_[hash:base64:3]!sass?sourceMap')
}
```

When I check the style inspector in chrome, I got this

<img width="417" alt="screen shot 2016-10-13 at 7 05 04 pm" src="https://cloud.githubusercontent.com/assets/538657/19348430/0e5a9114-9178-11e6-8960-0c9e6e36f703.png">

You can see all styles derive from bundle.css, that's not what I want from source map,  I was expecting something like below
<img width="369" alt="screen shot 2016-10-13 at 7 09 55 pm" src="https://cloud.githubusercontent.com/assets/538657/19348547/ae366a3c-9178-11e6-91a3-d59a099459a8.png">

The second picture is what I expect result of source map enabled, css rules derive from respective file name in which the rules reside. Base on the recommended config I can't get that result. Any advices?

**Comment by dvkndn** [comment]
Hi @craigcosmo I think this is a CSS Loader issue, maybe this will help you: https://github.com/webpack/css-loader/issues?utf8=✓&q=source%20map%20is%3Aissue

**Comment by gajus** [comment]
@dvkndn is right. This is off-topic for react-css-modules.
