### ISSUE TITLE
Disable `styles` property?

### ISSUE THREAD

**Issue by FezVrasta** [gajus/react-css-modules#189]
Is there a way to tell CSSModules to avoid to pass the `styles` prop to the decorated component?

**Comment by gajus** [comment]
> Is there a way to tell CSSModules to avoid to pass the styles prop to the decorated component?

Not at the moment, no.

It can be done. However, then you wouldn't be able to access the styles object.

**Comment by FezVrasta** [comment]
Yes that's the idea :)

Are you open to PRs?

**Comment by gajus** [comment]
What would this achieve?

**Comment by FezVrasta** [comment]
Lot of times in our team we pass properties down to the children element with `<div {...this.props} />` and we always need to strip `styles` off from `props` to avoid React warnings about unrecognized HTML attributes.

Also, we don't really use `styles` prop that much, so it would be better for us to enable it only when we need it.

**Comment by gajus** [comment]
> It even causes confusion when you pass the props down to another styled component that suddenly loses its styles.

This has been addressed on `react-css-modules@4.0.0`.

See https://github.com/gajus/react-css-modules/issues/58#issuecomment-247804849

Therefore, this shouldn't be a problem.

> Also, we don't really use styles prop that much, so it would be better for us to enable it only when we need it.

As long as you understand the implications\*, I think this is a reasonable request. PR is welcome.

> \*The implications are that `this.props.styles` will not always be the same as the `styles` that have been passed to the constructor of the `react-css-modules` when decorating the component.
> See https://github.com/gajus/react-css-modules/tree/9eee86d2d58ad273a7644dc62db54d0865c93f2e#extending-component-styles.

**Comment by FezVrasta** [comment]
Thanks for the reply, I don't understand how the problem has been addressed, how do you strip the `styles` prop from `this.props`?

**Comment by gajus** [comment]
> It even causes confusion when you pass the props down to another styled component that suddenly loses its styles.

This problem has been solved.

If you do `<ChildComponent {...this.props} />`, `styles` property will not be passed to the child because it is not enumerable.

**Comment by FezVrasta** [comment]
Ah! Ok this is awesome, thanks then!

**Comment by gajus** [comment]
Are you not getting this issue though?

> [..] we always need to strip styles off from props to avoid React warnings about unrecognized HTML attributes.

In theory, react-css-modules should still trigger this error when it sets the `styles` property.

**Comment by FezVrasta** [comment]
It shouldn't throw errors if it doesn't set it when applied with `{...this.props}` right?

I mean:

````
const myComp = (props) => <div {...props} />
CSSModules(styles)(myComp)
```

Doing so, `div` will not have `styles` right?

**Comment by gajus** [comment]
Oh... I misunderstood the issue. Yes, thats correct, `<div>` in the above example will not get the `styles` property from `props`. Note, that you can still access it `props.styles` in the component itself.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Enumerable_attribute

(I misused the term "not itterable". I meant "non enumerable".)
