### ISSUE TITLE
Lodash as dependency

### ISSUE THREAD

**Issue by Goblinlordx** [gajus/react-css-modules#192]
I submitted a PR a short time ago and was told to look at the closed PRs and issues.  I did so and looked through them and I saw 2 common responses.

  First being that You are not pulling in the entire lodash library.  This might be true... but you are still pulling in a significant portion of it for what seems to be simple type checking and some string manipulation which functions in js already exist for.

  The second type of response I saw was the overhead was negligible.  To this, I will say that is most definitely not what I am seeing.

  I created a branch from master and added webpack as a bundler so I could check the resulting bundle size in a more production like build.  I then merged that branch into the branch I build where lodash was removed as a dependency.  These branches can be found here:
[bundler](https://github.com/Goblinlordx/react-css-modules/tree/bundler)
[bundler-rm-lodash](https://github.com/Goblinlordx/react-css-modules/tree/bundler-rm-lodash)

Below are pre-minified build results:

**master branch with bundler**
```
Goblin@Main MINGW64 ~/Dev/react-css-modules (bundler)
$ npm run build:bundle

> react-css-modules@4.0.0 build:bundle C:\Users\Goblin\Dev\react-css-modules
> webpack

Hash: 1cb25d534049628c7216
Version: webpack 1.13.3
Time: 7333ms
    Asset    Size  Chunks             Chunk Names
bundle.js  285 kB       0  [emitted]  main
    + 192 hidden modules
```

**bundle after lodash is removed**
```
Goblin@Main MINGW64 ~/Dev/react-css-modules (bundler-rm-lodash)
$ npm run build:bundle

> react-css-modules@4.0.0 build:bundle C:\Users\Goblin\Dev\react-css-modules
> webpack

Hash: 51c32699f34123ca12a1
Version: webpack 1.13.3
Time: 4768ms
    Asset    Size  Chunks             Chunk Names
bundle.js  158 kB       0  [emitted]  main
    + 44 hidden modules
```

  By my count, this most certainly does not seem to be "negligible".  ~128kB added because of lodash and nearly 2x the size.  To be fair these are both really non-production results as they are not minified and such... so below are the production style bundle results:

**master branch with bundler (production style build)**
```
Goblin@Main MINGW64 ~/Dev/react-css-modules (bundler)
$ npm run build:bundle:prod

> react-css-modules@4.0.0 build:bundle:prod C:\Users\Goblin\Dev\react-css-modules
> webpack -p

Hash: 2629cf882aa8a3ece14d
Version: webpack 1.13.3
Time: 11654ms
    Asset     Size  Chunks             Chunk Names
bundle.js  57.7 kB       0  [emitted]  main
    + 189 hidden modules
```

**bundle after lodash is removed (production style)**
```
Goblin@Main MINGW64 ~/Dev/react-css-modules (bundler-rm-lodash)
$ npm run build:bundle:prod

> react-css-modules@4.0.0 build:bundle:prod C:\Users\Goblin\Dev\react-css-modules
> webpack -p

Hash: 69932d563a7e2775ba98
Version: webpack 1.13.3
Time: 6379ms
    Asset     Size  Chunks             Chunk Names
bundle.js  29.8 kB       0  [emitted]  main
    + 41 hidden modules
```

  ~28.1kB only coming from lodash after minification (weighing in at 189 modules vs 41) and still nearly 2x the size of the build with lodash removed.  I really fail to see how 2x the size is negligible overhead.

  Is there some other way this should be being bundled to prevent this "overhead"?

**Comment by gajus** [comment]
First of all, thank you for taking time to do the research and raise the issue.

> By my count, this most certainly does not seem to be "negligible". ~128kB added because of lodash and nearly 2x the size. To be fair these are both really non-production results as they are not minified and such... so below are the production style bundle results:

The biggest problem with this benchmark is that you assume that none of the dependencies in your project (and their dependencies recursively) depend on lodash. In practise, most of the projects I have been working on have dependency on lodash somewhere along the way.

**Comment by Goblinlordx** [comment]
Tthis is not a project?  This is only this repo.

**Comment by gajus** [comment]
I am sorry, I don't understand your last commend.

**Comment by Goblinlordx** [comment]
This is not another project.  I took this repo ran:
```npm i -D webpack```
Created a config file for it... and ran webpack.

**Comment by Goblinlordx** [comment]
As far as projects using lodash I have seen this often but I tend to purposefully avoid using lodash on client code because of the size.

**Comment by Goblinlordx** [comment]
I am not sure what part exactly is different but the other package I commonly use that I can find which pulls in any part of lodash is redux.  Redux built and minified which includes whatever it pulls in (only seem to be isPlainObject from lodash).  Redux-react pulls in isPlainObject as well from lodash.  Other than that though this seems like the only thing I can find pulling in lodash.  The common stuff I am using on client for my projects are: React, redux, react-redux, react-router.  Pretty much everything else except a few one off packages are just for building (webpack, loaders, babel, presets, plugins, etc) which don't really tend to add much to client code.

**Comment by gajus** [comment]
@Goblinlordx I have raised your concern with the lodash team.

https://github.com/lodash/lodash/issues/2785

Lets wait to see what the outcome of that conversation is.

**Comment by Goblinlordx** [comment]
Your effort is much appreciated. :+1:.  I must say, even with this complaint, I really appreciate your contribution with this package ^^.

**Comment by gajus** [comment]
@Goblinlordx 

See https://github.com/lodash/lodash/issues/2785#issuecomment-258218841

I hope this solves your problem.

If not, then this issue will be addressed when lodash v5 comes out.

**Comment by Goblinlordx** [comment]
Mind if I PR something to just add this information to the readme? This way others will know size of lodash imports can be reduced using this method until it is addressed via lodash v5.

**Comment by gajus** [comment]
> Mind if I PR something to just add this information to the readme? This way others will know size of lodash imports can be reduced using this method until it is addressed via lodash v5.

Absolutely. Sounds very reasonable. I'd be curious to know the build size too.
