### ISSUE TITLE
why is lodash a full dependency?

### ISSUE THREAD

**Issue by tdfairbrother** [gajus/react-css-modules#193]
I really like this module but I am curious as to why lodash is installed as a full dependency? After installing in my app and analysing the bundle size, my app has grown by more than 100 kb (uncompressed & minified).

Size of react-css-modules codebase = 17kb, size of lodash = 104kb.

Looking through the package, these are the only used functions.
isObject, isFunction, isArray, isUndefined, isBoolean, trim, filter, assign

Perhaps it is better to install the individual lodash functions (eg. https://www.npmjs.com/package/lodash.isfunction) or just use pure JS polyfills.

I don't mind making a pull request if this is just something that has been overlooked.

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/issues/192
