### ISSUE TITLE
Can't add property classname object is not extensible

### ISSUE THREAD

**Issue by eric7578** [gajus/react-css-modules#200]
`react css modules can't add property classname object is not extensible`

I got this error on android native browser, but this could not be solved by this issue (https://github.com/gajus/react-css-modules/issues/150), since I would like to use babel-polyfill for redux-saga.

**Comment by geryit** [comment]
@eric7578 did you find a way to fix this? I'm seeing the same error in my next.js project

**Comment by eric7578** [comment]
@geryit sorry for may late reply. 
I didn't solve this. Instead, I use styled-components.

**Comment by francorisso** [comment]
I've the same problem ONLY with nested divs for some reason:

```
<div sytleName="some">
  <div styleName="other">...</div>
</div>
```

**Comment by gajus** [comment]
This project is no longer actively maintained. I suggest inspecting https://github.com/gajus/babel-plugin-react-css-modules.

**Comment by jpaulsen-apixio** [comment]
@gajus Is this being phased out? If so I need to change my webpack to support the new structure. Don't see that information on the readme.md.

**Comment by gajus** [comment]
> Don't see that information on the readme.md.

It is literally the first thing in the README.md.
