### ISSUE TITLE
errorWhenNotFound doesn't work

### ISSUE THREAD

**Issue by NE-SmallTown** [gajus/react-css-modules#203]
the doc says that "when styleName cannot be mapped to an existing CSS Module",but the true is it doesn't work and cause the root element empty,no error and warning in console.**I can't locate which styleName isn't mapped to an existing CSS Module**,so I just look up every component one by one,that's so bad.

Is this a bug?If so,please fix that,thanks a lot. 

The shortcut is below:

[shortcut](http://www.blog.ne-smalltown.com/commonUpload/react-css-module-bug.gif)

**Comment by NE-SmallTown** [comment]
@gajus sorry to bother you,do you have any thought about this 'bug'?

**Comment by gajus** [comment]
There is not supposed to be any logs during the compile time. However, there are supposed to be warnings in the web console. Have you tried looking into the source code of react-css-modules to understand the issue?

If you want compile time errors, you'd need to be using https://www.npmjs.com/package/babel-plugin-react-css-modules

**Comment by NE-SmallTown** [comment]
>  However, there are supposed to be warnings in the web console. 

I know it should be,but i can't see any warning in my project.

My expectation is same with the official example,I clone this repository and run it,the shortcut is below:

[the shortcut](react-css-module-pr2.gif)

You can see that there is **Uncaught Error: "xxxxxxxxx" CSS module is undefined**,this is that I wanted.And this is very important and helpful.Because I can locate where I should modify according the error.

And I notice that the example doesn't install babel-plugin-react-css-modules,but you mention it.So it brings some puzzles to me.

Could you explain this more detailedly? Thanks a lot.

**Comment by NE-SmallTown** [comment]
I notice something at line:40 in generateAppendClassName.js:

```
if (className) {
    appendClassName += ' ' + className;
} else if (errorWhenNotFound === true) {
    throw new Error('"' + styleNames[styleName] + '" CSS module is undefined.');
}
```

I add 'debugger' in the source code above,I am sure the `throw new Error('"' + styleNames[styleName] + '" CSS module is undefined.');` statement is excuted,but after that,no error is thrown.It seems like something intercept the error log but I don't know what's that.

I update the react version of react-css-modules-examples to make sure the consistency of my project.And then I debug again,I observe the call stack of chrome devtools and I don't see any difference between the react-css-modules-examples and my project.But the true is there is no error log in my project and the react-css-modules-examples does.

So I am very confusing about it.Could you give me some thought?Thank you very much.

**Comment by NE-SmallTown** [comment]
I run my project in other browers and the error appears in the console,so I think maybe it's the brower's bug,and I ask some people,they said yes.
