### ISSUE TITLE
Importing a partial generates more classes

### ISSUE THREAD

**Issue by richardgorman** [gajus/react-css-modules#205]
I have the following code:

**Button.scss for Button Component**

```
@import '../utility/margin';

.button {
 ...
}
```

The outcome is that a css module is generated for every class that is inside the import.
Why is that?

**The Result:**

```
.Button_mart-0__2mMaIFbwL_ {
  margin-top: 0rem;
}

.Button_mart-1__19UdEiV8VA {
  margin-top: 0.25rem;
}

.Button_mart-2__3-mlpiVRuQ {
  margin-top: 0.5rem;
}

.Button_mart-3__2Qb7sDZvmM {
  margin-top: 0.75rem;
}

.Button_mart-4__2i1dZ5FkVh {
  margin-top: 1rem;
}
```

**Comment by gajus** [comment]
Its SCSS that inlines all the classes in the file. Your CSS modules configuration is set to global by default (see https://github.com/css-modules/css-modules#exceptions).

**Comment by richardgorman** [comment]
I'm sorry but I don't understand what you meant.

**Comment by gajus** [comment]
Transpile this code to CSS:

```css
@import '../utility/margin';
```

Whats the output?

**Comment by richardgorman** [comment]
That would be:

```
.mart-0 {
  margin-top: 0rem;
}

.mart-1 {
  margin-top: 0.25rem;
}

.mart-2 {
  margin-top: 0.5rem;
}

.mart-3 {
  margin-top: 0.75rem;
}

.mart-4 {
  margin-top: 1rem;
}
```

**Comment by gajus** [comment]
> That would be:

Then what is the reason that the result:

```
.Button_mart-0__2mMaIFbwL_ {
  margin-top: 0rem;
}

.Button_mart-1__19UdEiV8VA {
  margin-top: 0.25rem;
}

.Button_mart-2__3-mlpiVRuQ {
  margin-top: 0.5rem;
}

.Button_mart-3__2Qb7sDZvmM {
  margin-top: 0.75rem;
}

.Button_mart-4__2i1dZ5FkVh {
  margin-top: 1rem;
}
```

surprises you?

**Comment by richardgorman** [comment]
I expected that when Button composes .mart-0 then it would use the same hash as when .mart-0 was used by another component. If it can't do that then oh well.

**Comment by gajus** [comment]
You are mixing apples and oranges. SCSS is simply inlining styles. There is no way for CSS modules to know that. To achieve what you want, you'd need to use composition, https://github.com/css-modules/css-modules#composition.
