### ISSUE TITLE
Support NODE_PATH (webpack resolver; absolute path)

### ISSUE THREAD

**Issue by FezVrasta** [gajus/react-css-modules#211]
Seems like it only handles relative paths, it would be nice to be able to use the webpack resolver or at least a set of options like the `path` option of postcss-import.

**Comment by gajus** [comment]
Thank you for the suggestion.

No, "absolute path" support will not be added.

I am a strong proponent of the idea that it is an anti-pattern.

**Comment by FezVrasta** [comment]
So it is a good pattern to have `'../../../../something` 🙄

**Comment by gajus** [comment]
> So it is a good pattern to have '../../../../something' 🙄

There is nothing wrong with it.

However, the fact that you have that, shows that you have unusual project structure.

I did a quick grep across all the projects I am working and I have found 0 `../../../../` matches. (Few `../../../` and a lot `../../`).

**Comment by FezVrasta** [comment]
structure:

```
src
- components
  - component
    - components (sub-components of big complex components)
  - domain
    - view
    - components (components dedicated to this specific domain)
      - component
      - component
```

Just few examples.

**Comment by gajus** [comment]
> I wouldn't exclude a feature from your module just because you don't need it.

I don't simply not use it: I am advocating against its use in any context.

As for your example, there is nothing there that would require `../../../../`.

**Comment by FezVrasta** [comment]
If I need a generic `Button` component (located under `src/components/Button` inside a view component (located under `src/components/domain/components/component`) I need `../../../`, to me anything more than `./` is just wrong, because it will break as soon I change the position of it (`./` assumes it requires a file that is tied to it and you will always move them together)

Also, I get lost trying to resolve the `../../../` thing 🤢
