### ISSUE TITLE
About empty class in css bug

### ISSUE THREAD

**Issue by NE-SmallTown** [gajus/react-css-modules#213]
If a class is empty(i.e. `.header {}`) in css,I find that the styles in `generateAppendClassName.js` is an empty object.So then it must be throw an error.

**Comment by gajus** [comment]
> So then it must be throw an error.

It should throw an error or it should not?

**Comment by NE-SmallTown** [comment]
@gajus Thanks for your reply.IMO,I thinks it should't.Because we usually write some empty class to divide our css structure in the design stage,maybe it's empty now but have something next day.In addition,in some less case,we still use something(i.e. `.namspace .class{color: red}`) like before we don't use css-modules.And here `.namespace` is an empty class

**Comment by gajus** [comment]
Are you using SASS loader?

**Comment by NE-SmallTown** [comment]
@gajus yes.This is my all config about css:

```
// ------------------------------------
// Style Loaders
// ------------------------------------

//  set normal css-modules（exclude src/styles）
webpackConfig.module.loaders.push({
  test    : /\.(css|scss)$/,
  exclude : project.paths.client('styles'),
  loader  : 'style!css?modules&importLoaders=1&localIdentName=   [name]__[local]___[hash:base64:5]!sass?sourceMap=true!postcss'
});

// set src/styles are global css
webpackConfig.module.loaders.push({
  test    : /\.(css|scss)/,
  include : project.paths.client('styles'),
  loader  : 'style!css!sass?sourceMap=true!postcss'
});

webpackConfig.sassLoader = {
  includePaths : project.paths.client('styles')
};

webpackConfig.postcss = [
  cssnano({
    autoprefixer : {
      add      : true,
      remove   : true,
      browsers : [ 'last 2 versions' ]
    },
    discardComments : {
      removeAll : true
    },
    discardUnused : false,
    mergeIdents   : false,
    reduceIdents  : false,
    safe          : true,
    sourcemap     : true
  })
];

```

**Comment by gajus** [comment]
It is an issue with SASS, not react-css-modules.

http://stackoverflow.com/questions/11837701/how-to-include-empty-classes-and-ids-in-sass-result

**Comment by NE-SmallTown** [comment]
@gajus Thanks
