### ISSUE TITLE
Proposal: New Approach to CSS Modules driven components

### ISSUE THREAD

**Issue by iddan** [gajus/react-css-modules#219]
Inspired by styled components: What if I could import a full component?
To determine the tag name I can mention it explicitly in my css:
```CSS
div.my-awesome-class-name {  }
```
And then import it as a div with matching className:
```JSX
import { MyAwesomeClassName } from './stylesheet.css';

**Comment by gajus** [comment]
Whats the benefit?

**Comment by iddan** [comment]
Less boilerplate code: instead of wrapping commonly used wrapper styled components using a convention or a specified (webpack) loader this can be done for you.

### Example
#### React CSS Modules
```JavaScript
import styles from './stylesheet.css';

const CommonWrapper = (props) =>
    <div {...props} styleName="common-wrapper"/>;
```
#### New Proposal
```JavaScript
import { CommonWraper } from './stylesheet.css'; ;
```

**Comment by gajus** [comment]
Not something I'd do for `react-css-modules`, but could be a separate project.

**Comment by gajus** [comment]
> Not something I'd do for react-css-modules, but could be a separate project.

The primary reason is performance. `react-styledcomponents` requires to wrap every single element in additional element. That doesn't scale well.

**Comment by iddan** [comment]
Just wanted to make sure it doesn't fit before starting another repo.
Thanks @gajus, you're awesome!
