### ISSUE TITLE
Component class name is lost w/ Babel & ES6 classes

### ISSUE THREAD

**Issue by jrunning** [gajus/react-css-modules#22]
Using react-css-modules with Babel and ES6 classes, the original component's class name is lost. As a result, React's console warnings (and other tools like React Developer Tools) become less useful:

> Warning: Failed propType: Required prop `data` was not specified in `_class`. Check the render method of `_class`.

I think something as simple as the following in [`index.js`](https://github.com/gajus/react-css-modules/blob/master/src/index.js#L14) would fix this issue, but there may be implications I haven't considered:

```js
functionConstructor = (Component, styles, options) => {
    const decoratedClass = class extends Component {
        render () {
            return linkClass(super.render(), styles, options);
        }
    };

    decoratedClass.displayName = Component.name;

    return decoratedClass;
};
```

**Comment by gajus** [comment]
This looks like a reasonable fix. What about suffixing the name to indicate that the component is using `react-css-modules`?, e.g.

```js
decoratedClass.displayName = `${Component.name}-react-css-modules`;
```

* Does the longer hame have implications for debugging?
* Does adding `react-css-modules` suffix improving debugging experience? (It makes it more explicit, in my opinion.)

**Comment by ahdinosaur** [comment]
@gajus in a rails + react project i work on, we're using `name` / `displayName` in how we attach React components to our existing views, so suffixing the name with `react-css-modules` would introduce the need for additional workarounds.

**Comment by jrunning** [comment]
I think annotating the `displayName` in some way as @gajus suggests would be a big win for debugging.

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/tree/3.2.1

**Comment by gajus** [comment]
I agree with @ahdinosaur in that `displayName` should not be affected.

`react-css-modules` is not a real "higher order component". It is extending the `render` method. The API and the behaviour of the component is not affected when using `react-css-modules`. (with exception of [added `styles` property](https://github.com/gajus/react-css-modules#extending-component-styles)). Therefore, adding or removing `react-css-modules` must not affect the code outside of the component itself.

**Comment by gajus** [comment]
What is the reason @jrunning and @ahdinosaur mention `name` property in addition to `displayName`? I cannot find documentation for that in React docs.

**Comment by ahdinosaur** [comment]
`name` is a property of the `Function` prototype

```js
function fn () {}
console.log(fn.name) // 'fn'
```

so also when using the es6 class sugar

```js
class Class {}
console.log(Class.name) // 'Class'
```

as in

```js
class Component extends React.Component {}
console.log(Component.name) // 'Component
```

**Comment by gajus** [comment]
I am aware of the `name` property as a property of the `Function` prototype. Does React use `name` property as a display name when `displayName` property is not defined?

**Comment by ahdinosaur** [comment]
idk the details of what React does with `name` or `displayName`. i guess the idea is that using `name` instead of `displayName` when using es6 classes is easier since it's less code, but even if we wanted to support `name` i have no idea how we could implement passing a static constructor name without compiling code. the current implementation using `displayName` is cool with me. :+1:

**Comment by gajus** [comment]
We could construct `displayName` using the value of `name` of the child component when child component does not define `displayName` property.

**Comment by gajus** [comment]
Whether thats a good idea or bad depends on whether React uses `name` property when `displayName` property does not exist.

**Comment by jrunning** [comment]
Yes, React uses the constructor's `name` property when `displayName` is absent. You can see it [at the end of this method](https://github.com/facebook/react/blob/0.13-stable/src/classic/element/ReactElementValidator.js#L53-L69), for example. For ES6 users I think react-css-modules should do the same. I'm not sure what @ahdinosaur means about compilation; my code at the top of this thread shows how to get the `name` property.

@gajus Your reasoning re: not modifying `displayName` seems sound.

**Comment by jrunning** [comment]
FWIW the 3.2.1 code doesn't look like it solves anything for me. In 3.1.x, the workaround is to set `displayName` after calling the decorator (this is what I do in my app currently):

```js
@CSSModules(styles)
export default class MyFoo extends React.Component {
  // ...
}

MyFoo.displayName = 'MyFoo'; // booooo
```

It's repetitive—and if I ever change the name of the class, I have to remember to change the last line as well.

With 3.2.1, my code now looks like this:

```js
@CSSModules(styles)
export default class MyFoo extends React.Component {
  static displayName = 'MyFoo'; // booooo

  // ...
}
```

It's still repetitive, and I still have to remember to change `displayName` if I ever change the name of the class.

If react-css-modules uses `name` in the absence of `displayName` the same way React does, then my code can look like this:

```js
@CSSModules(styles)
export default class MyFoo extends React.Component {
  // yay!
}
```

**Comment by gajus** [comment]
> If react-css-modules uses name in the absence of displayName the same way React does, then my code can look like this:

Thats what I was aiming for. Wanted to make sure that it is inline with React behaviour. Will push an update in couple of minutes.

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/react-css-modules/tree/3.2.2.

**Comment by jrunning** [comment]
It looks like these changes didn't make it into [`dist/index.js`](https://github.com/gajus/react-css-modules/blob/master/dist/index.js).

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/tree/3.2.3

**Comment by jrunning** [comment]
Works great! Thanks!

**Comment by ahdinosaur** [comment]
> I'm not sure what @ahdinosaur means about compilation

i was referring to if we wanted to return a class with the `name` set, not just `displayName`. since `Function.prototype.name` is a read-only property, i could only imagine doing this with 'compilation', i.e.

```js
function classWithName (name) {
  return eval((`"use strict"; class ${name} {}`))
}
```

but that would be crazy. :stuck_out_tongue_closed_eyes:
