### ISSUE TITLE
Create Flow definitions for React CSS Modules

### ISSUE THREAD

**Issue by rsolomon** [gajus/react-css-modules#221]
Just noting this here for documentation. I've created a Flow definition for ReactCSSModules over at the flow-typed repository:  https://github.com/flowtype/flow-typed/pull/711

If it looks good, I'm happy to create a pull request and merge it here as well.

**Comment by gajus** [comment]
> If it looks good, I'm happy to create a pull request and merge it here as well.

Please do. Lots of love for #Flowtype here.
