### ISSUE TITLE
Property 'styleName' does not exist on type 'HTMLProps<HTMLDivElement>'.

### ISSUE THREAD

**Issue by fariyAhill** [gajus/react-css-modules#223]
I want to use css-modules in .tsx file,but got this error message.Here is my code.
![wx20170324-113612](https://cloud.githubusercontent.com/assets/12928690/24279646/194114c6-1086-11e7-9150-16f8fcdceacb.png)

 And tsconfig
`    "compilerOptions": {
        "target": "es5",
        "moduleResolution": "node",
        "jsx": "react",
        "experimentalDecorators": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "allowSyntheticDefaultImports": true,
        "allowJs": true,
        "sourceMap": true,        
}`

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/issues/147

**Comment by varHarrie** [comment]
Same problem, but have no idea.

https://github.com/gajus/react-css-modules/issues/147#issuecomment-270360401
