### ISSUE TITLE
Unknown prop styleName

### ISSUE THREAD

**Issue by creaux** [gajus/react-css-modules#227]
Hello,

I found many of similar issues but i didn't find exactly solution for this one.

```
Warning: Exception thrown by hook while handling onBeforeMountComponent: Error: Warning: Unknown prop `styleName` on <h1> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

Is that possible somehow when I running JEST to cleanup those warnings? Is there any official solution? Maybe I realised put them out using babel, ignore them by jest (not sure whether its possible) or any other solution?

**Comment by FezVrasta** [comment]
```
"moduleNameMapper": {
      "^.+\\.css$": "identity-obj-proxy",
    },
```
