### ISSUE TITLE
Use this plugin with JSPM

### ISSUE THREAD

**Issue by f15gdsy** [gajus/react-css-modules#23]
Hi, this plugin looks great!
I'm wondering if it can be used with JSPM?
If yes how to setup?

**Comment by gajus** [comment]
https://github.com/jspm/jspm-cli/wiki/Installing-Packages

**Comment by f15gdsy** [comment]
The thing is, JSPM imports everything as js file as default. 
I tried install the plugin as normal package, but it does not work.

**Comment by gajus** [comment]
Sorry. I just realised that JSPM is a frontend package manager. No, react-css-modules cannot work with JSPM. Unless of course you are using `webpack` too. But then you wouldn't be using JSPM.
