### ISSUE TITLE
Regression (v4.5.1): Warning: flattenChildren(...): Encountered two children with the same key

### ISSUE THREAD

**Issue by hinok** [gajus/react-css-modules#245]
Hey,
We are using `react-css-modules` in our project and after upgrade to `4.5.1` some errors has started appearing related to duplicated keys, like:

```jsx
Warning: flattenChildren(...): Encountered two children with the same key, `Bar`. Child keys must be unique; when two children share a key, only the first child will be used.
    in tbody (created by App)
    in table (created by App)
    in div (created by App)
    in App
```
This issue doesn't exist in `v4.3.0` and this code is valid from `React` perspective.

```jsx
const items = [
  { text: 'Foo' },
  { text: 'Bar' },
];

const App = () => (
  <div styleName="master">
    <table>
      <tbody>
        {
          items.map(item => (
            <tr key={item.text}>
              <td>{item.text}</td>
            </tr>
          ))
        }
        <tr>
          <td>Static content</td>
        </tr>
        {
          items.map(item => (
            <tr key={item.text}>
              <td>{item.text}</td>
            </tr>
          ))
        }
      </tbody>
    </table>
  </div>
);
```

Demo with `4.5.1`: https://codesandbox.io/s/G60xxyqg7
Demo without `react-css-modules`: https://codesandbox.io/s/q2noMEZ2

Related commits by @le0nik :
- https://github.com/gajus/react-css-modules/commit/407cdb492e738d7194be4e6152742ddeacce4e20
- https://github.com/gajus/react-css-modules/commit/b51b1f3dbfe50a5bda5e61019d352122cf188c7d
- https://github.com/gajus/react-css-modules/commit/44746ac4f9b78161f1c64bd2272f0a17e57221d3

**Comment by gajus** [comment]
@le0nik Do you have time to take a look into this?

**Comment by le0nik** [comment]
@gajus sure, I'll look into this.

**Comment by gajus** [comment]
Thank you.

Thank you for reporting the issue @hinok.

**Comment by le0nik** [comment]
@hinok so you actually do end up with 2 children with the same key and you are ok with this and you just want the error not to appear, correct?

**Comment by gajus** [comment]
I wasn't sure about this either. Looking at the provided sample code I cannot tell whether React will assign unique IDs to items in the above example based on their position in vdom or not.

If that is the case, then no, I think we shouldn't do this – the error needs to stay.

**Comment by le0nik** [comment]
`React` and `React.Children.map` actually do assign unique keys to the elements, unfortunately. It prefixes them with the and index of the initial array. So first `tr` with key `Foo` will have a key `.0:$Foo` and second `tr` will have key `.2:$Foo`(it's in the 3rd child array). So there is no way to support the situation above while not changing the keys and supporting non-array iterables. Should we revert the PR that unprefixes the child elements?

**Comment by hinok** [comment]
> @hinok so you actually do end up with 2 children with the same key and you are ok with this and you just want the error not to appear, correct?

It's not only about getting errors in the console.
More important for me is that something which should be rendered, magically disappears.

Look at the [demo](https://codesandbox.io/s/G60xxyqg7) with `react-css-modules`, items are rendered only once, not twice.That's the main problem for me that something is not rendered.

> React and React.Children.map actually do assign unique keys to the elements, unfortunately.

The questions is whether is okay for you to change the behaviour how React works.
In my understanding, If I can do certain things in pure React, I should be allowed to do the same things with `react-css-modules`.

**Comment by gajus** [comment]
The default behaviour must be compliant with React. This can be a configurable option. @le0nik is it worth having this as a configurable option?

Both scenarios are rather edge cases.

@le0nik Please advise how you suggest to proceed.

**Comment by le0nik** [comment]
@gajus I think it's not worth breaking functionality for one edge case for the sake of another. I suppose that this one is more common.

The case in #237 can probably be solved by using something like `_.endsWith()` to compare keys.
My case where the keys were changing with each re-render thus re-mounting the component is not reproducible now(most likely because of #243).

It's best to restore the native `React.Children.map`. I've done it in #246.

**Comment by gajus** [comment]
Thank you, @le0nik .

**Comment by le0nik** [comment]
No problem. Sorry for breaking your package :/

**Comment by hinok** [comment]
Thanks guys for fixing this so quickly. Cheers.
