### ISSUE TITLE
syntax for optional classes

### ISSUE THREAD

**Issue by lsentkiewicz** [gajus/react-css-modules#247]
I am using css modules in all my projects, and it works fine, but sometimes adding multiple classes require too much typing and changes.

Example:
Assume we create a simple component:
```jsx
function FooComponent() {
  return <div styleName="foo" />
}
```
After some time, we want to add a class `active` if `props.active` is true.
We can do:
```jsx
function FooComponent({active}) {
  return <div styleName={`foo  ${active ? 'active' : ''}`} />
}
```
or using `classNames`
```jsx
function FooComponent({active}) {
  return <div styleName={cn('foo', {active})} />
}
```

I am doing such steps very often:
- add `import cn from 'classnames'`
- CTRL+X `"foo"`
- fix attribute to `{cn...}`
- CTRL+V `"foo"`
- fix quotes
- etc

It's  very tedious work and I had to create some macros that help to convert it.

What if we could have a better syntax for css classes?
Example:

```jsx

function FooComponent({active}) {
  return <div $foo $active={active} />
}
```
We can prefix it with `$`. It's not a common practice to use $ for prop names, so I think we can reserve it.

Thoughts?

**Comment by gajus** [comment]
Thank you for the suggestion. However, I don't see this as part of `react-css-modules`. It would belong at a higher level abstraction, perhaps even Babel plugin.
