### ISSUE TITLE
PR #243 (v4.5.0) annihilates performance for React.PureComponents

### ISSUE THREAD

**Issue by rsolomon** [gajus/react-css-modules#252]
[React.PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent) attempt to optimize performance by doing a shallow comparison of old and new props. This works when a codebase sticks to purely immutable data structures that only change reference when they or their children have changed in some ways.

PR #243 added 2 major performance issues when combined with PureComponents: Cloning `Array`-typed Props in both `linkArray` and `linkElement`. The problem with `linkArray` was fixed in #244 so I won't expand on that. The problem that remains in `linkElement` is that, even if it doesn't find a valid React.Element (via `React.isValidElement`), it still returns a copy of the original Array-typed prop instead of a reference to the original Array.

That means that any PureComponent that uses CSSModules and relies on any Array-typed Props will see a *huge* performance hit when using v4.5 and above, being forced to re-render every time a parent component renders.

**Comment by le0nik** [comment]
An optimization could be added which would check whether there actually were any elements in the traversed array. If there weren't we can return the original array. Thoughts?

**Comment by rsolomon** [comment]
Confirmed fixed with v4.7.0 / PR #253 . Thank you @le0nik for the quick response.
