### ISSUE TITLE
About HoC with react-css-module

### ISSUE THREAD

**Issue by 951759534** [gajus/react-css-modules#264]
HOC and CSSModule used for a same Component with Decorator
display a error
React does not recognize the styleName prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase stylename instead. If you accidentally passed it from a parent component, remove it from the DOM element.

I need help 
Is it  a bug or I forget same config with CSSModule

**Comment by 951759534** [comment]
I see the problem   It About sort with Decorator  css Module should at the last

**Comment by hadnet** [comment]
This problem using decorator is still happening. It doesn't work when using the electron-react-boilerplate.
