### ISSUE TITLE
LinkClass found  elementShallowCopy is not frozen while elementShallowCopy.props is frozen

### ISSUE THREAD

**Issue by mengxingshike2012** [gajus/react-css-modules#266]
Hi gajus,
when prepareing our new project with react16,  we got error with react-css-modules.
As I say in the the title ,  please refer to the picture.

<img width="802" alt="wx20180224-230510 2x" src="https://user-images.githubusercontent.com/4207708/36631671-4f903d14-19b7-11e8-8bb5-487a89944b59.png">

**Comment by mengxingshike2012** [comment]
I think I have found the problem
when using with the latest react-hot-loader, the override method of react.children.only will change the result of object.isForzen. [#874](https://github.com/gaearon/react-hot-loader/issues/874)

**Comment by derpoho** [comment]
Same problem here. Is there any fix available?
