### ISSUE TITLE
Can react-css-modules be used with Sass, but without Webpack?

### ISSUE THREAD

**Issue by basher** [gajus/react-css-modules#268]
Hi... 

Your docs say that [browserify can be used instead of webpack](https://github.com/gajus/react-css-modules#browserify), and that [preprocessors are also supported](https://github.com/gajus/react-css-modules#sass-scss-less-and-other-css-preprocessors).

However, browserify requires [css-modulesify](https://github.com/css-modules/css-modulesify) which does not support Sass, and is still experimental. Hmmm.

Instead, I've been trying **babel-plugin-react-css-modules**, but have had issues with parsing CSS and Sass with browserify / babelify via NPM scripts - detailed in [issue-162](https://github.com/gajus/babel-plugin-react-css-modules/issues/162).

What I'm trying to achieve is a simple React scaffold for a UI library that does not need webpack / gulp / etc, and that supports CSS Modules and Sass.

And help / guidance will be much appreciated.

**Comment by gajus** [comment]
This project is no longer actively maintained.

Note that while Browserify is supported, it might have shortcomings such as lack of SASS support.

**Comment by basher** [comment]
OK. Thanks @gajus 

Are you still actively maintaining babel-plugin-react-css-modules?

Are you able to assist with https://github.com/gajus/babel-plugin-react-css-modules/issues/162 ?
