### ISSUE TITLE
react-css-modules causes modifying "key" property of the component children

### ISSUE THREAD

**Issue by vitaliymaz** [gajus/react-css-modules#285]
Using react-css-modules with [Ant Design Menu](https://ant.design/components/menu/) or rc-menu causes a bug with menu item selecting. 
Considering the code:
```jsx
<Menu selectedKeys={['2']} styleName="menu">
    <MenuItem key={'1'}>1</MenuItem>
    <MenuItem key={'2'}>2</MenuItem>
    <MenuItem key={'3'}>3</MenuItem>
</Menu>
```
Based on MenuItem key, Menu knows which item should be selected. But, because the react-css-modules those keys will be modified. 
https://github.com/gajus/react-css-modules/blob/5d1bf06726645798b13fba6642e15b134bf42cff/src/linkClass.js#L53
This code will force React to modify keys, details - https://stackoverflow.com/a/47030407/7714626

Also, I've created a small app to reproduce the bug https://github.com/vitaliymaz/reproduce-css-modules-bug
Replace this line
https://github.com/vitaliymaz/reproduce-css-modules-bug/blob/7bfa423de6f574ab367784d2266abc3b681e8ab8/src/App.js#L21
by the previous one and the bug will be reproduced. 

Proposing not to use React.Children.map() and use React.Children.forEach() instead. 
I can work on PR for this issue if nobody minds.

**Comment by gajus** [comment]
> I can work on PR for this issue if nobody minds.

If it does not break existing behaviour, go for it.

**Comment by vitaliymaz** [comment]
@gajus, could you share status on this issue. Are you going to merge my PR or it requires some additional work?

**Comment by vitaliymaz** [comment]
@gajus, thank you!
