### ISSUE TITLE
Usage without webpack

### ISSUE THREAD

**Issue by tp** [gajus/react-css-modules#37]
While `webpack` seems like the best choice today, I am wondering whether it would make sense to drop the hard dependency on it and allow for something more modular.

How about a simpler higher-order component that just loads the CSS file and embeds the final CSS in the output HTML?

**Comment by gajus** [comment]
`webpack` is not a dependency of `react-css-modules`.

Any module bundler that supports [CSS modules](https://github.com/css-modules/css-modules) can be used. At this point in time, the only competing module bundler is Browserify. Support for Browserify is already documented in the [`README.md`](https://github.com/gajus/react-css-modules#browserify).

**Comment by gajus** [comment]
> How about a simpler higher-order component that just loads the CSS file and embeds the final CSS in the output HTML?

Assuming you are referring to client side, this would require CSS modules implementation in client side (load CSS document and rename all CSS classes). This would get even more complicated if you were to support import statements within the CSS modules.

If you are referring the build process, then this is what the bundlers do already.
