### ISSUE TITLE
Handling modifiers in CSS modules

### ISSUE THREAD

**Issue by javivelasco** [gajus/react-css-modules#38]
I am building a complex component where you need to handle state depending on the user interaction, e.g. a Slider that has a `pressed` state when the user is dragging a knob.

I used to have a `.root` local class and a global `.pressed` class used as a modifier. In my React component, I was building a `className` like this:

```js
render() {
    let className = style.root;
    if (this.state.pressed) className += ' pressed';
    return <div className={className}>...</div>;
}
```

And being the style definition `:local(.root).pressed`.

I'm starting to integrate React CSS Modules and, since it embraces local classes and now by default all styles are local, I realized that maybe this is not the best approach.

Another way would be to build `styleName` attribute including modifiers in the name, for example generating `styleName='root-pressed'`. This class would extend `root` and override properties for the pressed status.

I can still use the first approach with React CSS Modules adding a **local** class name for pressed state and using it as a modifier:

```js
render() {
    let className = style.root;
    if (this.state.pressed) className += ` ${style.pressed}`;
    return <div className={className}>...</div>;
}
```

Maybe this is a good approach but the problems solved by React CSS Modules are going to still be there since the `pressed` class is included directly in the `className`.

What is the best approach?

**Comment by soyjavi** [comment]
+1

**Comment by gajus** [comment]
You are supposed to use [class composition](https://github.com/gajus/react-css-modules#class-composition), i.e. a single CSS class for every state of the element. This is the CSS modules way.

However, you can continue to compose/extend CSS modules as you used to using `allowMultiple` option, https://github.com/gajus/react-css-modules#allowmultiple.
