### ISSUE TITLE
Declare peerDependency with React 0.14.0-rc1?

### ISSUE THREAD

**Issue by lukewestby** [gajus/react-css-modules#40]
I realized today that for the change to accept stateless function components, the property checked at https://github.com/gajus/react-css-modules/blob/master/src/index.js#L18 to determine if the function is a constructor for a React Component is not available in 0.13.x. Should this library declare that 0.14.0-rc1 is a `peerDependency`, or should we implement a backward-compatible solution for detecting React classes instead?

**Comment by gajus** [comment]
What about just adding

```
"peerDependencies": {
  "react": ">=0.14.0"
},
```

constraint?

**Comment by lukewestby** [comment]
It looks like the `isReactClass` property is actually going to change to `isReactComponent` before the 0.14.0 stable release, so it seems like that method of detecting React classes isn't exceptionally reliable right now. I also think we should come up with a more robust detection method so that React 0.13.x users can also continue to benefit from this library. I should have looked into support for that property more before using it, I apologize!

I looked at how React detects stateless function components internally and it requires actually attempting to instantiate the component against its props, context and updater which we can't do because we don't have access to those.

A simple enough workaround until it becomes more clear how to detect a `React.Component` derivative is to look at `Component.prototype` to see if it exists (arrow functions have no prototype) and then check `Component.prototype.render` as every React component that requires CSS Modules should have a `render` method. I'll submit a PR for this shortly.

Thanks!

**Comment by lukewestby** [comment]
Fixed in ed3b28c25d2a0b07dde5fe9de69d1ea4691909de

**Comment by jayphelps** [comment]
(Since this ticket didn't include the symptoms of using 0.13.x with 3.3.1--3.5.0, adding the keywords so others can find it.)

Because classes in 0.13.x don't have `isReactClass`, you will receive `Uncaught TypeError: Cannot call a class as a function` because it incorrectly believes it's doesn't extend from `React.Component` and tries to call your class as a function inside `wrapStatelessFunction()`.

To fix, simply upgrade to 3.5.1+
