### ISSUE TITLE
Stateless components don't preserve propTypes or defaultProps

### ISSUE THREAD

**Issue by clessg** [gajus/react-css-modules#46]
You can use `propTypes` and `defaultProps` on a stateless function component. Unfortunately, it seems that they aren't preserved:

```javascript
const Bar = ({ greeting }) => (
  <div styleName="root">
    {greeting}
  </div>
);

Bar.propTypes = {
  greeting: PropTypes.string.isRequired
};

export default CSSModules(Bar, styles);
```

Is this expected behavior? I suppose I could do `const Bar = CSSModules(() => <div />)` and then add the `propTypes`, but I decided to file an issue just in case.

**Comment by lukewestby** [comment]
@gajus I think a simple `Object.assign()` from the inner function to the outer function in `wrapStatelessFunction()` should accomplish this

**Comment by gajus** [comment]
Sorry, this missed my radar.

Where is this documented in React documentation?

**Comment by gajus** [comment]
Found it https://facebook.github.io/react/docs/reusable-components.html#stateless-functions

**Comment by clessg** [comment]
Check out the 0.14 announcement from a few days ago: http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components

Not explicitly mentioned in the docs for some reason AFAIK.

**Comment by ahdinosaur** [comment]
from @clessg's link: "Functional components do not have lifecycle methods, but you can set .propTypes and .defaultProps as properties on the function."

**Comment by gajus** [comment]
3.6.0 has been published. Everyone say thank you to @lukewestby
