### ISSUE TITLE
serverside rendering example with composing

### ISSUE THREAD

**Issue by bdefore** [gajus/react-css-modules#48]
I've been trying to make serverside rendering work. I suspect it's not inherent to this project, though. When using `composes` in styles results in a classname that has a require block inside it, causing serverside rendering to fail to match clientside rendering. I'd love to see an example that gets around this problem.

https://github.com/erikras/react-redux-universal-hot-example/issues/184

**Comment by pauldijou** [comment]
Here is what we did to enable it on server side:

```javascript
require('css-modules-require-hook')({
  generateScopedName: function (exportedName, filename) {
    return loaderUtils.interpolateName(
      { resourcePath: filename }, // loaderContext
      // Keep in sync with the webpack config CSS loader
      '[name]_[local]_[hash:base64:5]',
      {
        content: exportedName + ' ".' + filename + '"',
      }
    ).replace(/\[local\]/gi, exportedName);
  },
});
```

And the webpack loader:

```javascript
loader: 'style!css?modules&importLoaders=1&localIdentName=[name]_[local]_[hash:base64:5]',
```

**Comment by gajus** [comment]
Thank you @pauldijou

**Comment by nightire** [comment]
@pauldijou I'm sorry but what is the `loaderUtils` indicates for?

**Comment by gajus** [comment]
@nightire https://github.com/webpack/loader-utils

**Comment by nightire** [comment]
@gajus Ah, that make sense now, thank you!
