### ISSUE TITLE
react-router activeClassName behaviour

### ISSUE THREAD

**Issue by olegakbarov** [gajus/react-css-modules#49]
I try to make a menu wiget with React-router and CSSModules. Got some trouble with class composition.

Linked components follows: `<Link to="/" styleName="item" activeClassName="active">`

...and result CSS looks like this: `class="item___yGoHfVhvZc active"` and no styles of `active` are applied.

Probably there's an elementary solution, but i'm a little stuck.

**Comment by gajus** [comment]
What is the implementation?

**Comment by olegakbarov** [comment]
Kudos to @faergeek! the solution is extremely simple:

Import active class from stylesheet:
` import styles, { active } from './styles.styl'; `

...and load it as follows:  `activeClassName={active}`

**Comment by faergeek** [comment]
Sorry for taking your time, the issue is resolved.

**Comment by gajus** [comment]
Thats wrong... You must use styles property of the component. The styles object that you import can overwritten at any time using styles property. Not to mention that you don't need to refer to an object in this scenario at all. Just have youClassActive class in ICSS.

**Comment by faergeek** [comment]
What's the purpose of the styles prop? Can you describe in a few words?

**Comment by faergeek** [comment]
Also I don't think that prop should or can be overwritten at all.

**Comment by gajus** [comment]
It is in the documentation "extending... [something]". I am on the phone, sorry.

**Comment by olegakbarov** [comment]
> Just have youClassActive class in ICSS.

`activeClassName` is react router specific attribute

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/blob/master/README.md#extending-component-styles

**Comment by gajus** [comment]
In that case use this.props.styles.active.

**Comment by olegakbarov** [comment]
> In that case use this.props.styles.active.

what's the important difference with this:

`import styles, { active } from './styles.styl';` and `activeClassName={active}`

**Comment by gajus** [comment]
Refer to the section of the documentation I have mentioned earlier.

**Comment by dciccale** [comment]
having `activeStyleName='active'` makes more sense no?

**Comment by elisechant** [comment]
`className={styles.link} activeClassName={styles.active}`
