### ISSUE TITLE
CSSModules does not see css property when uses stylus mixin

### ISSUE THREAD

**Issue by A11oW** [gajus/react-css-modules#54]
Hi, I use sylus preprocessor and when I wrote somethink like that
```
@import '../mixins';

.title
  widget-header()
```
CSSModules shows an error, that does not see .title

That's bug or normal?

**Comment by gajus** [comment]
You said that you are using a preprocessor. Then what is the the CSS that is being loaded? Thats the only bit thats relevant to debug the issue.

**Comment by A11oW** [comment]
just simple css
```
widget-wrapper()
  margin-bottom 12px
  padding 16px
  border-radius 5px
  background-color #fff
  box-shadow: 0 1px 1px rgba(0,0,0,0.05);
```

**Comment by A11oW** [comment]
ouch it's my fail. just wrong name of mixin. Sorry.

**Comment by ktquez** [comment]
@A11oW 
As you set up Webpack using stylus to react-css-modules?
You have any particular configuration?

Thanks

**Comment by A11oW** [comment]
@ktquez no any magic.
I use these packages: ```"style-loader", "stylus", "stylus-loader", "css-loader", "postcss-loader"```.
In webpack config:
```
...
      resolve: {
        extensions: ['', '.js', '.styl'],
      },
...
      { test: /\.css$/, loader: 'style!css' },
      { test: /\.styl$/, loader: 'style!css?modules&localIdentName=[local]___[hash:base64:10]' },
      { test: /\.styl$/, loaders: ['postcss', 'stylus'] },
```

In component:
```
import styles from './styles.styl';
import cssmodules from 'react-css-modules';
...
@cssmodules(styles)
export default class Agency extends React.Component {
...
}
```
