### ISSUE TITLE
Question: How does this work with jspm?

### ISSUE THREAD

**Issue by amalahussein** [gajus/react-css-modules#56]
We would like to use the ICSS pattern for our project, and use react-css-modules, however I'm confused at where this project (https://github.com/geelen/jspm-loader-css-modules) fits into the mix with React CSS Modules? Thanks in advance, and great work so far!

**Comment by amalahussein** [comment]
Also, it looks like jspm-loader-css-modules is broken for the latest release of jspm, I added this module, do you know if react-css-modules will work with this systemjs plugin https://github.com/systemjs/plugin-css?

**Comment by lukewestby** [comment]
`react-css-modules` actually comes in after the loading step so it should work well with just about any loader and bundler. The point at which this module connects with the loader is that the `CSSModules` function expects that you are passing it an object which maps readable classnames to generated ones. It looks like `plugin-css` doesn't provide that object so you may need to wait for or contribute a fix for `jspm-loader-css-modules`.

**Comment by amalahussein** [comment]
@lukewestby I see, and I think your right. So, assuming jspm-loader-css-modules is fixed, do I still need react-css-modules? I'm just trying to understand what this project is doing, that I wouldn't get from jspm-loader-css-modules?

Many thanks Luke!

**Comment by lukewestby** [comment]
This section of the README highlights the benefits of using this library: https://github.com/gajus/react-css-modules#whats-the-problem

What you get is a cleaner and more powerful way of associating your imported classnames with the elements they style, as well as the ability to continue using React's `className` prop as needed for global classnames. Personally, my favorite aspect of the lib is that it will throw an error if you give it a `styleName` that doesn't exist on your styles object, saving you from confusing spelling errors

**Comment by amalahussein** [comment]
Oh I see, very cool. But I can't use this with just the css-plugin, and I need to wait for the jspm-loader-css-modules to get fixed?

**Comment by lukewestby** [comment]
From looking at the `css-plugin` source code, it looks like it will inject your styles into the DOM for you, but it won't build the ICSS classname map. Having the ICSS classname map is key to the usefulness of this lib, so you'll need to use `jspm-loader-css-modules` or something like it to get it.

**Comment by amalahussein** [comment]
Gotcha....hummm. Its kinda of strange that its broken for such a popular bundler. But thanks Luke, that really helps, do you know of any other tools that create an ICSS classname map that are bundler agnostic? I found this but again its not very clear to me where it fits into the css-modules puzzle https://www.npmjs.com/package/css-modules-loader-core

**Comment by gajus** [comment]
There is an existing issue on the topic of JSPM, https://github.com/gajus/react-css-modules/issues/23.
