### ISSUE TITLE
Working with a CSS framework

### ISSUE THREAD

**Issue by mr-wildcard** [gajus/react-css-modules#57]
This isn't directly related to react-css-modules, but I'm working on project with a similar stack and I'm planning to use CSS Modules.
I'm having difficulty wrapping my head around how to combine CSS modules in conjunction with a CSS framework like Foundation or TB.

Say I have this stateless component function:

```javascript
var Header = () => (
	<header styleName="root">
		<div className="small-10 columns">
			<img styleName="logo" src="/images/logo.png" alt="Logo" />
		</div>
		<div className="small-2 columns">
			<a href="/logout" styleName="logout" className="button tiny">
				<i className="icon-logout"></i>
				Logout
			</a>
		</div>
	</header>
);
```

All `styleName`'s are correctly scoped to my component. But, `small-10`, `columns`, `button`, `tiny` are Foundation's classes, `icon-logout` comes from a custom fontello build. These classes are used pretty much everywhere in my project. 

I could simply append another `<link href="my-custom-foundation-build.css" rel="stylesheet"/>` into the `<head>` of my document, but I feel like this is not what CSS modules are trying to teach me :)

What is the recommended way to deal with this ?

**Comment by Duan112358** [comment]
[use the global feature of css modules](https://github.com/webpack/css-loader), or just skip the shared style in webpack loader's configration

**Comment by gajus** [comment]
Just extend your ICSS using [`composes`](https://github.com/css-modules/css-modules#dependencies) with the framework. Then you will be able to use all framework classes via `styleName`.

While there is nothing wrong with extending your ICSS with framework CSS, you should avoid using multiple styleNames and instead rely on [Class Composition](https://github.com/gajus/react-css-modules#class-composition) at the ICSS level.

**Comment by Duan112358** [comment]
@gajus what if i use a third part UI lib ? The className will mismatch due to the css modules's local feature

**Comment by gajus** [comment]
If you include it as ICSS (CSS Module), then there will be no mismatch.

**Comment by Duan112358** [comment]
another question:
i don't want to extract css out of js, just bundle with js using webpack. so I my loader config is following:
```
{
   test: /\.scss$/,
   loader: 'style!css?modules&importLoaders=1&localIdentName=[name]__[local]__[hash:base64:8]!sass'
}
```

the i got the local css as expected
```
<style>
.index__container__3r59lySx {
  margin: 10px;
  padding: 10px;
  background-color: #efefef; }

.index__message__3q49NKFZ {
  text-align: center; }

.index__btn__3GLpSqBT {
  border-radius: 2px;
  border: none;
  box-shadow: none;
  text-align: center;
  padding: 5px 10px;
  line-height: 1em; }
</style>
```
but the className doesn't mapped onto DOM
```
import React, { Component } from 'react'

import styles from './index.scss'

class Hello extends Component {
    constructor(){
        super();

        this.state = {
            message: 'hello world'
        }
    }

    sayHello(e){
        this.setState({
            message: 'Hey, life is a struggle.'
        });
    }

    render(){
        return <div className={styles.container}>
            <div className={styles.message}>
                { this.state.message }
            </div>
            <button className={styles.btn} onClick={this.sayHello.bind(this)}>Say Hello</button>
        </div>
    }
}

export default Hello
```
I guess the mapping back is done by extract-text-webpack-plugin,  is true or not?

Or, does react-css-modules can work without extract-text-webpack-plugin.

I just wanna the features just like Instangram does, so cool!

**Comment by mr-wildcard** [comment]
Thanks you all for your help.
I ended up using a custom .css build from Foundation, then use it to compose each of my local styles.

@Duan112358, `className` allows us to apply global styles declared "somewhere" else than those locally scoped inside a component. In fact, correct me @gajus if I'm wrong, `className={styles.message}` doesn't result into anything because react-css-module expects `className` value to be a string in order to append it to locally computed styles.

```javascript
// so basically, something like this:
styleName="{styles.container}" className="container"

// will produce this class attribute content:
class="index__container__3r59lySx container"
```

See: https://github.com/gajus/react-css-modules/blob/master/src/linkClass.js#L84

This simply keeps consistency with React `className` API.

**Comment by Duan112358** [comment]
@mr-wildcard Thks

**Comment by roylee0704** [comment]
@mr-wildcard I'm not sure if I have the same problem as you, say if I were to use css framework like `TB`, `flexiboxgrid`, or `semantic-ui`, how should I `required()` them into the javascript and avoid getting parse by `css-module`? As I wish to use `className` for css frameworks.

Btw I have the following webpack-config, and I wasn't sure if I'm doing it correctly, mixing up own custom css in conjunction with css frameworks.

```javascript
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]')
      }
```

**Comment by mr-wildcard** [comment]
> how should I required() them into the javascript and avoid getting parse by css-module

You can't. If you require a css file within your component, `css-loader` will automatically import the entire CSS framework + prefix every selectors with a namespaced hash. (You could get around by tweaking the loader configuration with `exclude` or `include`, but this doesn't seem to be a reliable solution.)

This also happens if you use `composes` :
```css
/* component/Product.css */
.root {
     composes: container from '~semantic.css'
}
```

...or if you `@import` a file with a preprocessor:
```css
@import ~foundation/components/global

.root {
     ...
}
```

In both cases, you get the entire CSS framework included in your component's styles.

I honestly spent too much time finding a way to compose nicely with CSS external libs.
I started another react project last week with `react-css-modules` + Semantic UI + pure css, I ended up building a `semantic.css` file with the least dependencies possible in it, then included it in the `<head>` of my document. (while in dev)
By doing this way, I often need to use `:global` to override Semantic UI styles, but now I can easily play with local `styleName` and put Semantic UI classes inside `className`.
FWIW, I only use `ExtractTextPlugin` in production.. I had some troubles with hot reloading.

Hope this helped you.

**Comment by roylee0704** [comment]
Thanks for taking up time to reply :) 
Yes, indeed it cleared up most of my confusion. 

Just to clarify, correct me if i'm wrong, any third party frameworks should be included under `<header>`, but not to `require()`them.

I have another question, 
>  This also happens if you use composes :

So say if I want to override a particular style of that framework, what should I do since `compose` would results in `webpack` crawling the rest of the css framework and prefix every selector with a namespaced hash?

**Comment by roylee0704** [comment]
Oh I just found the answer on top,

> Just extend your ICSS using composes with the framework. Then you will be able to use all framework classes via styleName -- @gajus  

Correct me if I'm wrong again, if I want to avoid namespaced hash for any css frameworks, I can no longer feed them into `webpack` and compile into a single `bundle.css`? 

Or it's a good practice to not compiling css frameworks and normal css into a single `bundle.css`?

**Comment by mr-wildcard** [comment]
> Just to clarify, correct me if i'm wrong, any third party frameworks should be included under <header>, but not to require()them.

(you meant `<head>` ? :)) You can. This is not "the" way, I'm just confortable with this solution.
Don't forget to concat every css files and minify the final one during production build.

> So say if I want to override a particular style of that framework, what should I do since compose would results in webpack crawling the rest of the css framework and prefix every selector with a namespaced hash?

Use `:global([css-framework-selectors-here])` to override global styles.
This how I'm dealing with Semantic UI right now:
```javascript
const MyComponent = () => {
    return (
        <div styleName="root" className="ui segment">
            ...
       </div>
    )
}
```
```css
/* MyComponent.css */

/* I'm overriding that way because I want to remove Semantic UI .segment padding. */
:global(.ui.segment).root {
    padding: 0;
}

/* Otherwise just target your component */
.root {
    ...
}
```

**Comment by gajus** [comment]
> Correct me if I'm wrong again, if I want to avoid namespaced hash for any css frameworks , I can no longer feed them into webpack and combine as a single bundle.css?

Yes you can. ICSS/CSS Modules allow importing only specific classes from a document (https://github.com/css-modules/css-modules#dependencies).

The confusion is coming from the fact that you are trying to mix CSS Modules and global CSS. You should not. You should be using CSS composition. There should be not a trace of your framework global CSS classes in the end document, e.g.

```css
.root {
    composes: ui from './framework.css';
    composes: segment from './framework.css';
}
```

Then your document would simply look:

```js
const MyComponent = () => {
    return  <div styleName="root"></div>;
}
```

**Comment by mr-wildcard** [comment]
thx @gajus 
I didn't realize that at first and this makes my previous statement just wrong. I updated it in consequence.
I thought that using for example `composes: container from 'framework.css'` inside multiple css files, would import the entire framework into each component styles, thus, resulting in big duplication problems.
Instead, it just creates a simple, unique `framework__container_[hash]`. Perfect.
thx again

**Comment by roylee0704** [comment]
ahh, sheer enlightenment! thanks @mr-wildcard and @gajus . :)

Actually I have a react-component plugin based on a css-framework: [flexgridbox](http://goo.gl/vEuvYh), and initially I wasn't blending the css into the component, basically it has no css framework attached to it, at all. The plugin is a generator that generates react-component with relevant className(s) on it.

Therefore, If I understand you both correctly, I should instead include the css framework as part of the plugin (leveraging react-css-module), am I right? ;)

**Comment by ruhusobeje** [comment]
We are hitting the same issue. The webpack build goes fine. But hit by the scope and style conflicts
With React css modules, the styles are not applied entirely.
Following is the setup for our scenario:

We are building a third party widget. We cannot use iframe for the widget.
It is built using React and bundled using webpack.
We are using Semantic UI react components and Semantic UI less for styling.
Now, our widget will be embedded within CMS.
So we want to scope the CSS from Semantic UI so that it does not affect the parent website and parent website does not affect the styling for our widget.

Currently we scope it using the following less file:

  .widget {
    .widgetMixin() !important;
  }

.widgetMixin{


// /* Global */
& { @import "~semantic-ui-less/definitions/globals/reset"; }
& { @import "~semantic-ui-less/definitions/globals/site"; }


/* Elements */
& { @import "~semantic-ui-less/definitions/elements/button"; }
/* All the remaining elements */
}
But this does not work and the components/elements gets the incorrect styles.
For ex: Dropdown does not open up and width is incorrect.

It will be helpful if anyone has any pointers regarding this.
Thanks :slight_smile:
