### ISSUE TITLE
Passing {...this.props} to a component breaks its own styles

### ISSUE THREAD

**Issue by mr-wildcard** [gajus/react-css-modules#58]
I had a component like this:

```javascript
import styles from './ParentComponent.css'
import React from 'react'
import CSSModules from 'react-css-modules';
import AnotherComponent from 'somewhere';

@CSSModules(styles)
class ParentComponent extends React.Component {

	render() {
		
		return (
			<div styleName="ParentComponent">
				<AnotherComponent {...this.props} />
			</div>
		)
	}
}
```

This breaks because of https://github.com/gajus/react-css-modules/blob/master/src/extendReactClass.js#L20

Thus, `AnotherComponent` receives `styles` props from its parent and can't find its own style properties.

Only workaround: manually put every props into a new object passed down to `AnotherComponent`:

```javascript
@CSSModules(styles)
class ParentComponent extends React.Component {

	render() {
		
		let propsNeeded = {
			props1: this.props.props1,
			props2: this.props.props2,
			props3: this.props.props3,
			props4: this.props.props4
			...
		}

		return (
			<div styleName="ParentComponent">
				<AnotherComponent {...propsNeeded} />
			</div>
		)
	}
}
```

**Comment by nodkz** [comment]
I got same problem. I think this is the lack in design.

I spent several hours to find problem. In the middle I want choose https://github.com/FormidableLabs/radium But I don't like its paradigm, so I come back to solve problem.

**So, right now I use such solution:**
```javascript
render() {
   <MenuList {...this.props} styles={undefined} />
}
```

I think it will be more clear for overriding child styles, use such prop name `overrideStyles`. When child's decorator get `styles` prop, it should simply omit them. Instead of this it should use `overrideStyles` prop.

After that we can safely use spreading of attributes `<MenuList {...this.props}>`. And if we will want to override child styles, just use such spreading `<MenuList {...this.props} overrideStyles={this.props.styles}>`

**BTW** if choose name `overrideStyles` it also does not solve problem. Because if we pass overrideStyles to child, and will use spreading for child of child, it also get style overriding. But such problems will occur much rarer. 

**So may by use merging in https://github.com/gajus/react-css-modules/blob/master/src/extendReactClass.js#L20?**:
```javascript
let styles = _.isObject(defaultStyles) ? defaultStyles : {};

if (this.props.styles) {
    styles = _.assign({styles}, this.props.styles);
} 

this.props.styles = styles;
```

**Comment by gajus** [comment]
A simple solution:

* Require `useStyles` property to overwrite component styles.
* The higher-order component (react-css-modules) renames the property to `styles` and gives to the child.
* Using `...this.props` inside the child component to pass properties to yet another child component, will pass `styles` property (instead of `useStyles`) which has no meaning for further inheritance.

**Comment by gajus** [comment]
The only problem with the latter approach is that it is a breaking change.

**Comment by nodkz** [comment]
Any plans for a release date of 4.0.0?

**Comment by gajus** [comment]
I would like to add more breaking changes to one release. That said, there haven't been any other requests that would affect the API.

I will leave this issue open for a few days. If there are no suggestions for a better implementation, better name or ... I will implement it.

**Comment by gajus** [comment]
The thing that I do not like about this proposal is that it introduces unexpected behaviour (transforming property names) at the expense of a lazy developer. After all, you could simply do this:

```js
<AnotherComponent {..._.assign({}, this.props.styles, {styles: null})} />
```

**Comment by nodkz** [comment]
I with pleasure will do it )) cause react-css-modules is the best solution for component styling.

For me, like newbie, its implicit behaviour of overriding children styles led to confusion. Cause console error just report, that it can not find a some css classname in child component. And need deep diving to understand, that problem occures in the parent component.

**Comment by nodkz** [comment]
Also it will be great to have an ability to prepend/append styles in child component.
Probable props names are `prependStyles`, `appendStyles`, but they don't good correlate with decided property name `useStyles`. May be `replaceStyles` is better.

**Comment by bryanhelmig** [comment]
I ran into this myself by passing `{...this.props}` to children - resulting in "CSS module is undefined". It was a surprised and I burned a good half hour. Would definitely be :+1: on addressing this in some way.

**Comment by neverfox** [comment]
I agree that this seems like a non-issue, since React provides an idiomatic way to exclude certain props (no need for `_.assign` or a `propsNeeded` hack):

```
<AnotherComponent {...this.props} styles={null} />
```

If you're going to use a brute-force method of like `{...this.props}`, it falls to you to consider if that makes sense given what you know about the props and the mixins/decorators you're using that may modify them.

**Comment by neverfox** [comment]
That said, I sort of like the approach taken by `react-styleable` (a library attempt to do much the same thing as this one) which attempts to merge the override with the child's styles, throwing an error if the override contains styles that aren't part of the child's style map. This has the advantage of:

* Making it clear why things were failing
* Giving you the prepend/append feature mentioned by @nodkz 
* Seems to hold more to component isolation since the child will still assert as much of its local style as possible, rather than having it all blown away by a potentially underspecified override.

**Comment by gajus** [comment]
> throwing an error if the override contains styles that aren't part of the child's style map

That would not work with ICSS and composition pattern, because you are meant to have "private" classes that are used solely for mapping purposes.

**Comment by neverfox** [comment]
But it is working, in the technical sense, so I'm not sure I understand your comment. Do you mean that it violates the principles?

**Comment by gajus** [comment]
I am not familiar enough with `react-styleable` to comment, but if it uses CSS modules and is

> throwing an error if the override contains styles that aren't part of the child's style map

then that would violate principles of ICSS and composition pattern.

**Comment by neverfox** [comment]
As far as I know, ICSS doesn't have anything to say about what a developer does with two exported objects that they have in front of them. In your case, you overwrite one with the other. In the case of react-styleable, it compares the keys (not the values) and throws if a key is found on the provided prop that differs from the internal one.

**Comment by gajus** [comment]
Maybe I am misunderstanding you.

Are you suggesting that, given a default stylesheet, e.g.

```css
.foo {
    color: #f00;
}

.bar {
    color: #0f0;
}
```

and an implicit stylesheet that extends the default, e.g.

```css
.foo {
    color: #00f;
}

.baz {}
```

`react-styleable` will complain about the presence of `.baz` in the implicit stylesheet?

**Comment by neverfox** [comment]
Yes, to take the example from the OP, this would error:

```
import css from './ParentComponent.css';
import React from 'react';
import styleable from 'react-styleable';
import AnotherComponent from 'somewhere';

// css = { foo: "ParentComponent__foo__hash", bar:  "ParentComponent__bar__hash" }
// styleable will inject this into this.props.css

@styleable(css)
class ParentComponent extends React.Component {
    render() {
        return (
            <div className={this.css.foo}>
               <div className={this.css.bar}>
                 <AnotherComponent {...this.props} />  // includes this.props.css
               </div>
            </div>
        );
    }
}
```

```
import css from './AnotherComponent.css';
import React from 'react';
import styleable from 'react-styleable';

// css = { foo: "AnotherComponent__foo__hash", baz:  "AnotherComponent__baz__hash" }
// styleable will inject this into this.props.css

@styleable(css)
class AnotherComponent extends React.Component {
    render() {
        return (
             <div className={this.css.foo}>
               <div className={this.css.baz}>
               </div>
            </div>
        );
    }
}
```

```
Expected "this.props.css" to provide only overrides to the given stylesheet.  Selectors "bar" not included in the stylesheet keys, "['foo', 'baz']".
```

**Comment by vyorkin** [comment]
btw it also breaks if you use something like `react-motion`, e.g.:

```
import cn from 'classnames';

... skipped...

    return (
      <Motion style={animationStyle}>{s =>
        <div className={className} styleName='seek-bar' style={s}>
          <div className={containerClassName} styleName='container'}>

... skipped...
```

so I have to do this instead:

```
import cn from 'classnames';

... skipped...

return (
      <Motion style={animationStyle}>{s =>
        <div className={cn(className, styles.seekBar)} style={s}>
          <div className={cn(containerClassName, styles.container)}>

...skipped...
```

**Comment by adnasa** [comment]
I'm late to the discussion, 
but I consider it necessary to introduce a new option key `allowOverride` (defaults to false) on the WrappedComponent.
It would cover most of the cases I've encountered, especially in pure rendering components that should accept the whole `props` object from the parent.


```js
if (this.props.styles && options.allowOverride) {
  styles = this.props.styles
}
```

__usage__:
```js
export default CSSModules(Component, styles, {
  allowMultiple: true,
  allowOverride: true
})
```

**Comment by grrowl** [comment]
@gajus could your [simple solution](https://github.com/gajus/react-css-modules/issues/58#issuecomment-155098179) be inverted to avoid a major breaking change? i.e.

* in userland the property is `styles={}`
* CSSModules wrapper renames this to `__CSSModulesStyles` or whatever
* Internally, react-css-modules checks against this internal property

Although, it still doesn't fix the underlying trap of `{ ...this.props }` changing styling behaviour (I believe this is a widespread and correct use of spread), it would be more obvious to notice a "__CSSModulesStyles" (and hence debug).

I would prefer if we didn't have to pass down a implicit, secret property at all — that'd avoid the issue entirely — using context or traversing the tree differently.

**Comment by gajus** [comment]
> [@adnasa]
> but I consider it necessary to introduce a new option key  allowOverride  (defaults to false) on the WrappedComponent.

See @nodkz [comment](https://github.com/gajus/react-css-modules/issues/58#issuecomment-155095573):

> BTW if choose name  overrideStyles  it also does not solve problem. Because if we pass overrideStyles to child, and will use spreading for child of child, it also get style overriding. But such problems will occur much rarer. 

This is hardly a solution.

> [@growl]
> Although, it still doesn't fix the underlying trap of  { ...this.props }  changing styling behaviour (I believe this is a widespread and correct use of spread), it would be more obvious to notice a "__CSSModulesStyles" (and hence debug).

I am not following. How does presence of `__CSSModulesStyles` help to solve the problem? It does not address inheritance issue either (see the reply to @nodkz). Introducing a private value that appears out of nowhere would only further obscure the logic.

I agree with @nodkz and @neverfox that this is non-issue:

> I agreewith @gajus that this seems like a non-issue, since React provides an idiomatic way to exclude certain props (no need for `_.assign` or a `propsNeeded` hack):
> 
> ```
> <AnotherComponent {...this.props} styles={null} />
> ```
> 
> If you're going to use a brute-force method of like `{...this.props}`, it falls to you to consider if that makes sense given what you know about the props and the mixins/decorators you're using that may modify them. I wouldn't change anything in this regard.

I do not see the current behaviour as an issue.

**Comment by nodkz** [comment]
@gajus I found good solution for me, how to pass parent styles to children (override child style from parent) .

May be you found it interesting:

**Parent component**
```js
import React from 'react'
import withStyles from './withStyles';
import s from './ParentComponent.css'
import ChildComponent from './ChildComponent';

@withStyles(s)
class ParentComponent extends React.Component {
    render() {
        return (
            <div className={s.ParentComponent}>
                <ChildComponent {...this.props} s={s} />
            </div>
        )
    }
}
```

**Child component**
```js
import React from 'react'
import withStyles from './withStyles';
import s from './ChildComponent.css'

@withStyles(s)
class ChildComponent extends React.Component {
    render() {
        return (
            <div className={ss.ChildComponent}> // <------ `s` - only child style, `ss` - combined with parent styles 
                some data
            </div>
        )
    }
}
```

I am using `ss`prop name if I want to allow override child styles from parent. As u can see, I pass `s` prop from parent to child. `ss`-prop is creating  by `@withStyles`. Internally it combines child styles with parent styles passed from `s`-prop. 

And at last my `withStyles` code (forked from https://github.com/kriasoft/isomorphic-style-loader/blob/master/src/withStyles.js):
```js
import React, { Component, PropTypes } from 'react';

function withStyles(...styles) {
  return (BaseComponent) => class StyledComponent extends Component {
    static propTypes = {
      s: PropTypes.object,
    };

    static contextTypes = {
      insertCss: PropTypes.func.isRequired,
    };

    static displayName = BaseComponent.displayName || BaseComponent.name;

    constructor(props) {
      super(props);

      this.setState = (state) => this.refs.component.setState(state);
    }

    componentWillMount() {
      this.removeCss = this.context.insertCss.apply(undefined, styles);
    }

    componentWillUnmount() {
      this.removeCss();
    }

    render() {
      const parentStyles = this.props.s;
      if (parentStyles) {
        const combinedStyles = Object.assign({}, styles[0]);
        for (const key of Object.keys(combinedStyles)) {
          if (parentStyles.hasOwnProperty(key)) {
            combinedStyles[key] = `${combinedStyles[key]} ${parentStyles[key]}`;
          }
        }
        return <BaseComponent {...this.props} ss={combinedStyles} ref="component" />;
      }

      return <BaseComponent {...this.props} ss={styles[0]} ref="component" />;
    }
  };
}

export default withStyles;
```

**Comment by gajus** [comment]
I was thinking more about this.

What about simply passing `styles` property as non-enumerable?, i.e.

```
const Root = React.createClass({
    render: function () {
    	console.log('props.b #1', this.props.b);
    
        return <div>Hello, World!</div>;
    }
});

const props = {
	a: 'A'
};

Object.defineProperty(props, 'b', {
	value: 'B'
});

console.log('props.b #0', props.b);

React.render(<Root {...props} />, document.body);
```

This way the wrapped component would have access to the `this.props.styles` property, but doing `{...this.props}` would not pass it to the children. You could still pass it explicitly, e.g. `{...{styles: this.props.styles}}`.

Thoughts?

**Comment by nodkz** [comment]
I think such hack brings more problem in future. For debugging and testing - 100%. May be somebody use current behaviour already, and it breaks their code.

May be provide several decorators with different behaviour `@CSSModules`, `@CSSModulesWithoutParentStyle`.

**Comment by gajus** [comment]
I am not afraid of breaking the current behavior (as long as we follow the semver convention), neither is defining a property as non enumerable a hack.

I cannot fathom what difficulty it would cause for either debugging or testing either - the property is present, it is simply non-enumerable.

To me this sounds like a clear-cut solution to the issue.

**Comment by anru** [comment]
just fyi: for myself I wrote similar babel transformation (you can easily do it too via pretty good site http://astexplorer.net/ ) that doing all needed job (transforms style attributes to className attributes and merge them if necessary) at compile time.
In the end we have cleaner & faster code without such problems as this one.

**Comment by gajus** [comment]
> @anru 
> just fyi: for myself I wrote similar babel transformation (you can easily do it too via pretty good site http://astexplorer.net/ ) that doing all needed job (transforms style attributes to className attributes and merge them if necessary) at compile time.
> In the end we have cleaner & faster code without such problems as this one.

can you elaborate more what are you advertising?

**Comment by anru** [comment]
Transform this
```jsx
<div styleName="main" />
```
to this
```jsx
<div className={styles['main']} />
```

It's enough for me.

**Comment by gajus** [comment]
> Transform this
> ```jsx
> <div styleName="main" />
> ```
> to this
> ```jsx
> <div className={styles['main']} />
> ```
> 
> It's enough for me.
> 

Thank you for sharing. It is irrelevant to this discussion though. Please keep it on topic.

**Comment by clessg** [comment]
I like the idea of passing the `styles` property as non-enumerable. The current behavior is surprising and I've seen a few developers waste a nontrivial amount of time on it.

**Comment by gajus** [comment]
> I like the idea of passing the styles property as non-enumerable. The current behavior is surprising and I've seen a few developers waste a nontrivial amount of time on it.

I will leave this open until the end of May.

If no one chips in with valuable insights why this would be a terrible decision, I will release it in v4.0.0

**Comment by clessg** [comment]
Any update on this?

**Comment by gajus** [comment]
I will make a pre-release today, to see if it is breaking anything.

**Comment by gajus** [comment]
This change has been added to v4. `react-css-modules@4.0.0` has been published under beta channel.
