### ISSUE TITLE
Augment className generation logic

### ISSUE THREAD

**Issue by nsisodiya** [gajus/react-css-modules#59]
I like react-css-style as it generate unique className.
like this.

`.RateCalendarCell__dateCellBox___1_m9Q`

However , I am trying to build something where I need to add uniqueness like

`.nsisodiya_projectName_RateCalendarCell__dateCellBox___1_m9Q`

I want to add Developer and project name too !
any clue, how to do that ?

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules does not generate class names. It is the https://github.com/css-modules/css-modules implementation that does that. If you are using webpack, then it is most-likely that className generation algorithm is defined in the https://github.com/webpack/style-loader.
