### ISSUE TITLE
Cannot define multiple styleName's

### ISSUE THREAD

**Issue by StevenIseki** [gajus/react-css-modules#62]
I am having an issue trying to define multiple styleName's using react-css-modules.

`Uncaught Error: ReactElement styleName property defines multiple module names ("grid15 gridMd15").`

It is admittedly a bit of an edge case where I need multiple styles for responsive grids. I usually only need the 1 stylename.

```jsx
function Grids( props) {
    const { route } = props;
    return (
        <div styleName='grid'>
            <div styleName='grid15 gridMd15'><p>Fifths</p></div>
            <div styleName='grid15 gridMd15'><p>Fifths</p></div>
            <div styleName='grid15 gridMd15'><p>Fifths</p></div>
            <div styleName='grid15 gridMd25'><p>Fifths</p></div>
        </div>
    );
}
```

I can acheive the multiple classNames using css-modules as follows: 

```jsx
className={styles.grid25, styles.gridMd15}
```

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules#allowmultiple

**Comment by StevenIseki** [comment]
Aweome... Legend!

Funny that I was wrong with the above `className={styles.grid25, styles.gridMd15}` was not really working for me with CSS Modules, it just wasn't giving an error, and picked up only the second class.

I am now not sure how to use multiple classes with plain CSS Modules... but I am *very happy* it works well with react-css-modules. 

If anyone has any feedback on how to allow multiple without react-css-modules I would be keen to know out of interest.

**Comment by gajus** [comment]
> If anyone has any feedback on how to allow multiple without react-css-modules I would be keen to know out of interest.

```
className={styles.grid25 + ' ' + styles.gridMd15}
```

**Comment by StevenIseki** [comment]
Aha... thanks a lot
