### ISSUE TITLE
bypass react-css-module for some CSS file

### ISSUE THREAD

**Issue by nsisodiya** [gajus/react-css-modules#64]
I am using react-css-module ! but my project has two kind of files !
internal css files which I am writing which I want to load using react-css-module for unique class !
external css files which I want to load as it is

for example

```
import React, {Component} from 'react';
import styles from './EventCalendar.css';
import CSSModules from 'react-css-modules';
import DayPicker from "react-day-picker";
import "react-day-picker/lib/style.css";
```
This is my webpack.config.js

```
var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
	devtool: 'source-map',
	entry: {
		main: "./src/js/ui/index.js",
		worker: "./src/js/bl/worker.js"
	},
	output: {
		path: "temp/dist",
		filename: "[name].bundle.js"
	},
	plugins: [
		new ExtractTextPlugin('app.css', {
			allChunks: true
		})
	],
	module: {
		loaders: [
			{
				test: /.js$/,
				loader: "babel-loader"
			},
			{
				test: /\.css$/,
				loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]')
			}
		]
	}
};
```

I do not know how to proceed.. But right now, it is converting `react-day-picker/lib/style.css` also into local unique classes which I want to escape !

**Comment by nsisodiya** [comment]
currently I have solved the problem using like this 

```js
module: {
		loaders: [
			{
				test: /.js$/,
				loader: "babel-loader"
			},
			{
				test: /\.css$/,
				exclude: [/node_modules/],
				loader: ExtractTextPlugin.extract('style',
						'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]')
			},
			{
				test: /\.css$/,
				include: [/node_modules/],
				loaders: ['style', 'css']
			}
		]
	}```

It is now loading content of `react-day-picker/lib/style.css`  inside the <style> tag automatically !

Any comment on above approach ??

**Comment by gajus** [comment]
This question is non-*react-css-modules specific*. It is a generic webpack question.

**Comment by chapati23** [comment]
@gajus yes and no. basically everyone that follows the setup-instructions in the README and wants to use 3rd-party css will run into the problem. so it might actually be worthwhile adding a bullet-point to the readme on `Excluding 3rd-party CSS (e.g. animate.css) from react-css-modules`

i'm using @nsisodiya's method as well for 3rd-party css

**Comment by gajus** [comment]
I recommend against using `exclude` option for loaders. Prefer explicit import rules (i.e. `include`) over blacklist approach. Otherwise, those seeking an answer to this question will stumble upon this issue anyway (It ranks high in Google too)
