### ISSUE TITLE
Question: Is there any way to pass a prop from component to css class declaration?

### ISSUE THREAD

**Issue by reggi** [gajus/react-css-modules#65]
If I wanted to allow a color prop to effect the CSS what's the best way to do this? Do I have to use inline styles?

**Comment by gajus** [comment]
Please include code example

**Comment by StevenIseki** [comment]
I would refer you to this [question](http://stackoverflow.com/questions/34035820/using-css-modules-in-react-how-can-i-pass-a-classname-as-a-prop-to-a-component) but the basics of the answer are you can pass in a prop, and then just assign the prop to the styleName e.g. `'button' + ' ' + this.props.color` which would give you 'button blue' as the styleName.

```jsx
import React, { Component } from 'react';
import CSSModules from 'react-css-modules';
import styles from './Button.css';

class Button extends Component {

  render() {
    let color = 'light'

    if(this.props.color !== undefined){
    	color = this.props.color
    }
    let buttonStyle = 'button' + ' ' + color

    return (
      <button styleName={buttonStyle}>{this.props.text}</button>
    );
  }
};

export default CSSModules(Button, styles, {allowMultiple: true} );
```

**Comment by gajus** [comment]
Thank you @StevenIseki
