### ISSUE TITLE
ReferenceError: Can't find variable: Symbol

### ISSUE THREAD

**Issue by jonnyreeves** [gajus/react-css-modules#66]
Commit ff2bc9a has introduced a breaking change when running tests on [PhantomJS](http://phantomjs.org/):

```
ReferenceError: Can't find variable: Symbol
```

This error appears to have been introduced by the following code:

```js
const ITERATOR_SYMBOL = typeof Symbol === 'function' && Symbol.iterator;
```

I was able to work around this issue by adding the babel-polyfill package in the test bundle.js generated by webpack:

```
npm install babel-polyfill
webpack babel-polyfill **/*.spec.js --config webpack.config.js
```

**Comment by gajus** [comment]
This looks like the correct solution. There is nothing that can be done at the `react-css-modules` level as far as I can tell (please correct me if I am wrong).

Might be worth adding to the docs.

**Comment by vyorkin** [comment]
Sorry, but I just can't figure it out. I'm using babel 5.x and karma + phantomjs runner. [I already have](https://github.com/vyorkin/starter-kit/blob/master/karma.conf.js#L3) the `require('babel/register') hook and [it should require the polyfill automatically](https://github.com/vyorkin/starter-kit/blob/master/karma.conf.js#L3)

**Comment by vyorkin** [comment]
ok, I'll try to reproduce from scratch with minimal config

**Comment by export-mike** [comment]
Yeah I'm getting this error. It breaks as soon as I ```import CssModules from 'react-css-modules';``` without even calling. ``` export default CssModules(MyComponent, styles) ```

**Comment by export-mike** [comment]
Solved,I added require('babel-polyfill'); to the top of my test.webpack.js file:
```
require('babel-polyfill');
var context = require.context('./src', true, /-test\.js$/); // make sure you have your directory and regex test set correctly!
context.keys().forEach(context);
```

**Comment by vyorkin** [comment]
@export-mike yeah, the same, can confirm this works for me either

**Comment by export-mike** [comment]
yeah you just need to require('babel-polyfill') at the start

**Comment by alexmngn** [comment]
@export-mike Do you mind to show us some of your code? I have the same issue and I can't resolve it.
It's telling me that `require.context` is not defined.

**Comment by re54k** [comment]
Use polyfill will add codes not really need. This error is just caused by missing `typeof` check of `Symbol`, or not access it from `global`/`window`.
With webpack, can fix this by loader:

``` js
loaders: [
    {
        test: /isIterable/,
        loader: 'imports?Symbol=>false'
    }
]
```
