### ISSUE TITLE
Sourcemaps support

### ISSUE THREAD

**Issue by tiemevanveen** [gajus/react-css-modules#69]
Hi! 

Great package, been playing with it for the last days now and it works really great. 

The documentation gives no examples for sourcemaps support. But could one of you tell me if / how you use this package with sourcemaps?

I've also added a question on Stackoverflow about this: http://stackoverflow.com/questions/34434849/how-to-get-sourcemaps-working-for-react-css-modules

**Comment by gajus** [comment]
Add documentation https://github.com/gajus/react-css-modules#enable-sourcemaps

**Comment by tiemevanveen** [comment]
\0/
