### ISSUE TITLE
What benefit does react-css-modules provide over CSS Modules?

### ISSUE THREAD

**Issue by Jabher** [gajus/react-css-modules#7]
I'm using a similar approach, but with no extension packages, instead of that I'm utilizing less JS-ssy and more global approach by just using postCSS module 'postcss-modules-local-by-default'. No decorators, additional components and so on, just a bit of css sugar (by making selectors local by default) on compilation stage.

E.g. 

```javascript
import React, {Component} from 'react';
import style from './IntroCard.css';

export class IntroCard extends Component {
    render () {
        const {authorized, loading} = this.props;
        return <div
            className={`mdl-card mdl-shadow--2dp mdl-cell mdl-cell--12-col ${style.logoBackgroundContainer}`}>...</div>
```

and in webpack
```javascript
const STYLE_LOADER =
    `css-loader?localIdentName=${DEBUG ? '[name]__[local]___[hash:base64:5]' : '[hash:base64:5]'}!postcss-loader`;
const module = {
    loaders: [
        {
            test  : /\.css$/,
            loader: DEBUG
                ? `style-loader!${STYLE_LOADER}`
                : ExtractTextPlugin.extract('style-loader', STYLE_LOADER)
        },
       ...
```

It will work faster, weight less and so on.
Instead of working over this package making a boilerplate with properly configured webpack builder looks much better option.

**Comment by bdefore** [comment]
@Jabher While that approach is nice and succinct, none of the benefits listed in the README for this repo are solved by the example you provide:

* You are not forced to use the `camelCase` naming convention.
* You do not need to refer to the `styles` object every time you use a CSS Module.
* There is clear distinction between global CSS and CSS Modules, e.g.

```js
<div className='global-css' styleName='local-module'></div>
```

* You are warned when `styleName` refers to an undefined CSS Module ([`errorWhenNotFound`](#errorwhennotfound) option).
* You can enforce use of a single CSS module per `ReactElement` ([`allowMultiple`](#allowmultiple) option).

**Comment by gajus** [comment]
@Jabher Thank you for sharing your approach, though it would be more suitable as a blog post than an issue in this repository. @bdefore answer covers the benefits. If these benefits do not outweigh the cons for you, then there is no need to use react-css-modules. It is my opinion that react-css-modules is a nice abstraction that makes it easier to use CSS Modules and enables overall cleaner codebase.
