### ISSUE TITLE
Lodash 4 causing errors

### ISSUE THREAD

**Issue by bkonkle** [gajus/react-css-modules#79]
After updating to the latest version, I started getting errors like this:

```
Error: Cannot find module 'lodash/lang/isFunction'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/brandon/code/projectName/node_modules/react-css-modules/dist/index.js:7:20)
```

I believe the paths to each module were updated to drop the middle portion, like "lang" above (as indicated under the "More Modular" heading [here](https://github.com/lodash/lodash/releases/tag/4.0.0)). You may need to go through and update all of the paths.

If I have time tonight I'll submit a pull request for you, if you don't beat me to it. :-)

Thanks for sharing react-css-modules! It's great!

**Comment by gajus** [comment]
What react-css-version?

**Comment by bkonkle** [comment]
It was 3.6.7. I reverted back to 3.6.5 to resolve the issues.

**Comment by gajus** [comment]
3.6.8 have fixed this issue a few hours ago.

**Comment by bkonkle** [comment]
Aha - okay! Updated and confirmed, 3.6.8 does fix the issue. Thanks!
