### ISSUE TITLE
Apply styleName during the build process using automatically derived CSS Modules file

### ISSUE THREAD

**Issue by bdefore** [gajus/react-css-modules#8]
Could we DRY this up even further by inferring the path of the CSS/SCSS file from the name of the class? i.e. decorating a class `Foo` with `@CSSModules` would cause it to look for a `Foo.css` or `Foo.scss` relative to the same directory. That way we wouldn't even need the `import styles from './Foo.scss'` line, nor pass that to the decorator statement.

**Comment by adamdicarlo** [comment]
Hmm, how would you make sure Webpack could deal with determining statically which CSS/SCSS file needs to get included?

**Comment by gajus** [comment]
It should be a file with the same name and extension X (configured at the time of setting up the webpack plugin), e.g.

```js
new ReactCSSModules({
   extension: 'scss'
});
```

```
/Foo.js
/Foo.scss
/Bar/index.js
/Bar/index.scss
```

The corresponding files `Foo.scss` and `index.scss` would be loaded.

**Comment by adamdicarlo** [comment]
Ah, that makes sense, I was thinking of a component class decorator. Your way is much better!

I'm wondering how easy would it be to use a component built with ReactCSSModules? In terms of publishing "shared components" to npm (public or private registry). Would consumers need to use the component's "dist" (compiled down) version (which could lead to duplication of packages in your final bundle, if your component uses, e.g. Lodash, and so does my app)? Would they be able to import your JS directly... and if they did would they have to use the ReactCSSModules plugin? If so there might need to be an option for the plugin to only autoload scss/css for deps in node_modules or some such...?

**Comment by gajus** [comment]
@adamdicarlo Please open this as a separate issue. I will be happy to answer.

**Comment by stnwk** [comment]
+1

**Comment by gajus** [comment]
https://github.com/gajus/babel-plugin-react-css-modules

Looking for feedback.
