### ISSUE TITLE
Readme: "You have to use camelCase CSS class names"

### ISSUE THREAD

**Issue by matthiasfeist** [gajus/react-css-modules#81]
In the readme there is this sentence "You have to use camelCase CSS class names.". I don't really get why since this is not actually enforced, right? I mean I can use `styles['some__crazy--bem-selector']`

Or am I missing the point here?

**Comment by gajus** [comment]
If you are happy with using the quotes in brackets syntax, then yes, you can use hyphens in your CSS modules.

**Comment by matthiasfeist** [comment]
ah allright. thanks.
(well I wouldn't say "happy" but it works ;))
