### ISSUE TITLE
Lost styles in Safari on component update

### ISSUE THREAD

**Issue by majodev** [gajus/react-css-modules#89]
Hi!

First of all, thx for your nice work, it's a pleasure to work with it in our frontend stack.

However, I've encountered a nasty bug with react-css-modules (at least 3.7.0 and 3.6.1 are affected) in combination with Safari (Mac, latest Version 9.0.3 (11601.4.4)). It seems that classNames are not injected properly on component updates, leaving the component without any styles (it flickers at first). What's interesting, is that the issue resolves itself when opening Safari dev-tools...

I've [forked your react-css-modules-examples](https://github.com/majodev/react-css-modules-examples) to reproduce the issue (run in Safari).

![fail_in_safari](https://cloud.githubusercontent.com/assets/2149883/12732034/f88a3810-c933-11e5-9676-695357a60f01.png)

![works_with_devtools_open](https://cloud.githubusercontent.com/assets/2149883/12732042/01878e90-c934-11e5-93a2-7e5f50977c60.png)

**Comment by gajus** [comment]
I can confirm the issue. Started looking into it. The fact that it starts working miraculously as soon as you enable web dev tools does not help the debugging process.

**Comment by gajus** [comment]
Works:

```js
constructor(props) {
        super(props);

        this.state = {
            count: 0
        };

        setInterval(() => {
            this.setState({
                count: this.state.count + 1
            });
        }, 250);
    }
```

Sometimes works:

```js
constructor(props) {
        super(props);

        this.state = {
            count: 0
        };

        setInterval(() => {
            this.setState({
                count: this.state.count + 1
            });
        }, 100);
    }
```

Does not work:

```js
constructor(props) {
        super(props);

        this.state = {
            count: 0
        };

        setInterval(() => {
            this.setState({
                count: this.state.count + 1
            });
        }, 50);
    }
```

**Comment by majodev** [comment]
Hm, even with 250ms it does only sometimes work on my rather old macbook air. Sorry for this weird debugging situation...

**Comment by gajus** [comment]
I have managed to optimise the code to make it work with 50ms consistently. Will release a beta version in about an hour.

**Comment by gajus** [comment]
Please try this version:

```sh
npm install react-css-modules --tag beta
```

**Comment by majodev** [comment]
Seems to work a little bit better (50ms), but it still flickers randomly until about 300 steps, then loses its styles forever until the Safari devtools are opened.

**Comment by gajus** [comment]
@majodev Please try the latest version (3.7.4). You can simply run the example, since it is using it already. https://github.com/gajus/react-css-modules-examples

**Comment by majodev** [comment]
Nice work! I can confirm it's fixed. Closing...

**Comment by athomann** [comment]
I'm still having this issue on 3.7.4
