### ISSUE TITLE
ES7 decorator only works if it's nearest the export statement

### ISSUE THREAD

**Issue by bdefore** [gajus/react-css-modules#9]
I may very possibly be misunderstanding ES7 syntax, but I noticed that styles would silently fail to be applied if I used it in tandem with another decorator, in my case redux-form (https://github.com/erikras/redux-form)

This would style correctly:
```
@reduxForm('foo', fooValidators)
@cssModules(styles)
export default class Foo {
.
.
.
}
```

This would not:

```
@cssModules(styles)
@reduxForm('foo', fooValidators)
export default class Foo {
.
.
.
}
```

In either configuration, redux-form functioned as expected.

Either I'm not configuring that correctly, or one of these two libraries is not allowing another decorator to follow it.

**Comment by gajus** [comment]
I have brought this to the attention of the reduxForm maintainer. I have [tried](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20decB%20(sub)%20%7B%0A%20%20%20%20console.log('decB%20%2301'%2C%20sub)%3B%0A%20%20%20%20return%20(Component)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20console.log('decB%20%2302'%2C%20Component)%3B%0A%20%20%20%20%20%20%20%20return%20class%20extends%20Component%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20talk%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20'B'%20%2B%20super.talk()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%7D%0A%7D%0A%0Afunction%20decC%20(sub)%20%7B%0A%20%20%20%20console.log('decC%20%2301'%2C%20sub)%3B%0A%20%20%20%20return%20(Component)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20console.log('decC%20%2302'%2C%20Component)%3B%0A%20%20%20%20%20%20%20%20return%20class%20extends%20Component%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20talk%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20'C'%20%2B%20super.talk()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%7D%0A%7D%0A%0A%40decC()%0A%40decB()%0Aclass%20Foo%20%7B%0A%20%20%20%20talk%20()%20%7B%0A%20%20%20%20%20%20%20%20return%20'A'%3B%0A%20%20%20%20%7D%0A%7D%0A%0Aconsole.log(%20new%20Foo().talk()%20)%3B) replicating the issue using just cssModules. cssModules appear to be working as expected.

**Comment by erikras** [comment]
This would need some debugging. Examining the props in React devtools might be interesting.

This might be `cssModules`'s fault _if_ it's not crawling the whole component tree looking for styles to replace. If it's only looking at what is returned by its decorated component's render(), then you'd get this behavior. As long as it's passing all props along, I suppose there's nothing wrong with requiring that it be the innermost decorator.

It's entirely possible that this is reduxForm's fault, too. I'm just spitballing ideas.

**Comment by taurose** [comment]
As far as I can tell, the redux-form decorator creates a [HoC](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775) which doesn't extend the decorated class, but wraps it in another component with its own render method. I think that's rather common, so I'd just warn about it in docs, unless someone sees a way to work around that.

**Comment by bdefore** [comment]
That would explain things. Thanks @taurose

**Comment by gajus** [comment]
What is the reason for not extending render method like react-css-modules does it?

**Comment by erikras** [comment]
It's a philosophical difference, functional vs object oriented. The HoC pattern is a common one.

**Comment by gajus** [comment]
In this case, `react-css-modules` must be used as the last decorator in the chain (i.e. it must be the first one to wrap the component). This is not a bug in `react-css-modules`.

**Comment by tommedema** [comment]
How is this not an issue?

If you argue that some decorators must be used as the last in the chain, then you are also implicitly stating that these decorators are mutually exclusive to each other. Imagine if another decorator had the same requirement, then how could we use them together?

My current classes look like so:

    @autobind
    @connect(null, { revealActiveReviewAnswer })
    @cssModules(Bootstrap, { allowMultiple: true })
    export default class ReviewRevealButton extends Component {
        ...
    }

If other developers decide to add more decorators, it may cost them considerable time to discover this somewhat odd requirement.

**Comment by tommedema** [comment]
This is already causing issues, because for some reason the `autobind` decorator has the same issue.

I.e.: this will cause exceptions like `Uncaught TypeError: Cannot read property 'props' of null`:

    @autobind
    @cssModules(Bootstrap, { allowMultiple: true })

Whereas this will make autobind work but make cssModules fail:

    @cssModules(Bootstrap, { allowMultiple: true })    
    @autobind

Any suggested workaround until we find a better solution for this?

**Comment by gajus** [comment]
If you can think of an implementation that will solve the issue, a PR is welcome. I cannot think of a reasonable solution.

**Comment by tommedema** [comment]
@gajus I don't think whether we have a an answer ready or not should have any influence on if this is considered to be an issue. I don't have a solution right now, but I do think it is an issue.

That said, I will keep digging into this. Hopefully I can find a solution.
