### ISSUE TITLE
Cannot find module css module

### ISSUE THREAD

**Issue by dagatsoin** [gajus/react-css-modules#90]
I work with Meteor and React and trying to get react-css-modules working.

Note that my app uses Cordova.

I have a folder A where are Meteor & my React components.
I have a folder B where is Webpack.

So, I have managed to compile the final css with Webpack but I have an error in the Safari Developper Tool: `Error: Cannot find module './map.xss'` (map.xss is a css file. I renamed it to prevent Meteor concats it with the other css file.)

It seems that my component still wants to import the source file. How to prevent that ?

**Comment by gajus** [comment]
This sounds a lot like [`css-loader`](https://github.com/webpack/css-loader) issue.

**Comment by gajus** [comment]
@dagatsoin Please share your solution or a reference to an issue if you are tracking it elsewhere (for future reference).
