### ISSUE TITLE
Prototype functions names are considered an invalid style

### ISSUE THREAD

**Issue by c0** [gajus/react-css-modules#93]
First off, this lib is sweet!

I found that if I define a prototype function eg `Array.prototype.foobar = function () {}`, then this lib includes it when checking for valid class names and incorrectly throws an error that `foobar` is not a valid.

It looks like stems from the `for..in` loop in `generateAppendClassName`

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of)

```js
let iterable = [3, 5, 7];
iterable.foo = "hello";

for (let i in iterable) {
  console.log(i); // logs 0, 1, 2, "foo"
}

for (let i of iterable) {
  console.log(i); // logs 3, 5, 7
}
```

**Comment by gajus** [comment]
This simply requires adding [`hasOwnProperty`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) condition to the `for..in` loop.

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/blob/324f950f25eebbd042abd1b76576c693da159e6b/src/generateAppendClassName.js#L24

**Comment by c0** [comment]
Thanks @gajus!
