### ISSUE TITLE
React 0.13 complains about directly setting props

### ISSUE THREAD

**Issue by SohKai** [gajus/react-css-modules#95]
When using this with React 0.13, every component rendered emits a warning because of the [shallow copying of ReactElement](https://github.com/gajus/react-css-modules/commit/4b62f6dbe1e10b3efc4c6e9629f8a977549bf9c7):

```
Warning: Don't set the props property of the React element. Instead, specify the correct value when initially creating the element.
```

Most people are probably on React 0.14 where this isn't a problem, so maybe it's enough to document / use peer dependencies to suggest that everything before 3.7.1 is for >= 0.13 and everything after is >= 0.14?

**Comment by gajus** [comment]
It is suffice that this issue exists. Thank you for reporting it @SohKai.

**Comment by gajus** [comment]
> peer dependencies to suggest that everything before 3.7.1 is for >= 0.13 and everything after is >= 0.14?

I don't know of a way to do this programmatically. Am I missing part of the docs?

https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by SohKai** [comment]
Ah yeah, the only way I could think of doing it is to branch off of 3.7.0 and change the react dependency to be ~0.13 and release that as a 3.7 hotfix for react 0.13 users. I guess you could then rebase all the other changes after 3.7 on top of this branch to get a clean history but that's probably not necessary.
