### ISSUE TITLE
Apply styleName to DOM as property

### ISSUE THREAD

**Issue by alexmngn** [gajus/react-css-modules#97]
Hi,
Using `react-bootstrap`, in some cases we need to pass a DOM element as a property, in order for me to add an icon.
If I'm doing that, the `CSSModule` doesn't grab the `styleName="icon"` that I passed as a property.
Any suggestion how I could make this work?
Thanks

```
<NavDropdown
   eventKey={2}
   title={<span><span styleName="icon" className="fa fa-search"></span>Find</span>}
   id="basic-nav-dropdown"
>
```

**Comment by gajus** [comment]
This is both documented in README and has been asked many times on https://github.com/gajus/react-css-modules/issues.
