### ISSUE TITLE
react-css-modules leverages as existing CSS Modules implementation webpack css-loader.

### ISSUE THREAD

**Issue by minooo** [gajus/react-css-modules#98]
A little don't understand the meaning of this sentence:`react-css-modules leverages as existing CSS Modules implementation webpack css-loader.`

**Comment by gajus** [comment]
[css-modules](https://github.com/css-modules/css-modules) itself is just a spec. An example of a library that implements css-modules is [css-loader](https://github.com/webpack/css-loader). `react-css-modules` uses the functionality provided by `css-loader` to enable integration of CSS modules with React components.

The same could be said about other bundlers, e.g. [css-modulesify](https://github.com/css-modules/css-modulesify) browserify plugin.

**Comment by minooo** [comment]
Thank you very much!
